### ISSUE TITLE
git version fails to build on openSUSE

### ISSUE THREAD

**Issue by ahjolinna** [mpc-qt/mpc-qt#1]
here is the OBS build log: https://gist.githubusercontent.com/ahjolinna/3d0b8421403e6b541d40881e5e24cbbe/raw/8a33b86971e8e91e1e8b9f73308a80703e8c6fe7/mpc-qt.log

and here is .spec file https://build.opensuse.org/package/view_file/home:ahjolinna/mpc-qt/mpc-qt.spec?expand=1

**Comment by cmdrkotori** [comment]
Let me know if the fix works.

**Comment by ahjolinna** [comment]
didnt build, I got too different erros with leap 15.3 and tumbleweed 

leap: https://gist.github.com/ahjolinna/0aeb0aac07320e32168966c3eb9c6ca4
tumblweed: https://gist.github.com/ahjolinna/561b41a80f32971cbe38b10e046456e5

btw. I use git version of mpv https://build.opensuse.org/package/view_file/home:ahjolinna/mpv/mpv.spec?expand=1

**Comment by cmdrkotori** [comment]
Does it work now?

**Comment by ahjolinna** [comment]
both builds have now succeeded...thanks

PS. its nice to see you back .... I hope you are doing better
