### ISSUE TITLE
mpv-player is somehow freezing MainGuiThread

### ISSUE THREAD

**Issue by jps05** [mpc-qt/mpc-qt#10]
To reproduce: 
- add several files to the playlist and play the first one
- select the 2nd or 3rd file by mouse double click while video is playing --> no reaction and file 1 still playing
after stopping playback mouse double clicks will be recognized and other files will be played,
Do you have any idea?

**Comment by cmdrkotori** [comment]
Not a clue since I can't reproduce this on my end.
What files are you using and what's your desktop environment?

**Comment by jps05** [comment]
I compiled for macOS where the behaviour can be reproduced.

**Comment by cmdrkotori** [comment]
I can't legally develop software for macos without owning a mac, so I've decided to drop official support for macs.  Sorry, but it is what it is.
