### ISSUE TITLE
displaying a check mark next to the selected track in the menu

### ISSUE THREAD

**Issue by AdventurerRussia** [mpc-qt/mpc-qt#106]
there is a missing check mark next to the subtitle tracks and audio, video streams that are currently selected for playback!
it would be nice if you added this.

[image](https://github.com/mpc-qt/mpc-qt/assets/14019010/549b09c4-529c-4caf-9bc1-a74577f95959)

![image](https://github.com/mpc-qt/mpc-qt/assets/14019010/67676706-bf86-4e17-ae5c-605755e58aea)

what does this icon do, it doesn't have any description on hover?
![image](https://github.com/mpc-qt/mpc-qt/assets/14019010/1acafde8-f0c0-40ef-a373-39c4648b559e)
upd 
I realized that she turns off subtitles, she lacks a description and some more understandable icon that these are subtitles.
https://cdn-icons-png.flaticon.com/512/565/565286.png

**Comment by tbertels** [comment]
Here's what it looks like now:

![image](https://github.com/user-attachments/assets/a9f5ac38-f535-4ed9-a4eb-e42356697217)
