### ISSUE TITLE
Playlist Window Doesn't Remember State

### ISSUE THREAD

**Issue by peppersgc** [mpc-qt/mpc-qt#109]
I uncheck the box under view to turn off the playlist window, but it opens again every time I open a new video file. It screws up scaling on ultrawide monitors outside of fullscreen, also known as distracting big black bars.
![Screenshot_1](https://github.com/mpc-qt/mpc-qt/assets/24569463/6c3cfd7e-7812-40f6-9002-5cf9bd373b63)

**Comment by cmdrkotori** [comment]
There's was a bug in the Qt6.7beta (that has since been fixed) which causes that.

Anyway, works on my machine.
