### ISSUE TITLE
After playback not persisting

### ISSUE THREAD

**Issue by SlouchyButton** [mpc-qt/mpc-qt#11]
When you choose action after playback in Play->After playback->Everytime (any of the options) the setting is reset after relaunch of the mpc-qt.
Option you select is not persisting, there is no error in console (except cannot load libcuda.so.1 which probably have nothing to do with that since I am on AMD gpu the error is expected).
Probably not yet implemented feature?

EDIT seems like function `mainWindow->setPlayAfterAlways();` is made and will work with this:
`mainWindow->setPlayAfterAlways(Helpers::PlayNextAfter);`, but it is not ever called.

I do not have experience with C++, so I wouldn't be able to fix this in nice way using techniques u guys are using with Qt, so I would rather leave it to you.

**Comment by cmdrkotori** [comment]
It's not implemented because mpc-hc doesn't remember it either.

**Comment by SlouchyButton** [comment]
> It's not implemented because mpc-hc doesn't remember it either.

It does, well not exactly how I described it, but it has an option in settings for default value, which is not implemented in mpc-qt either tho, well at least I have not found it.

**Comment by cmdrkotori** [comment]
Reopening because this is a functional difference in mpc-qt.
