### ISSUE TITLE
A more fitting app icon?

### ISSUE THREAD

**Issue by Yasand123** [mpc-qt/mpc-qt#111]
MPC-QT is cool but the smiley face icon doesn't reflect what the application is about. I think even a generic video player icon could be more fitting? CC0 icons, something like [this one](https://iconduck.com/emojis/128826/clapper-board), is free option.

**Comment by cmdrkotori** [comment]
Yep. I'm a programmer, not an artist. The best icon you're going to get out of me is programmer art.  That said if someone wants to make a PR for a new icon I'm willing to look at it.

**Comment by ezvision** [comment]
> Yep. I'm a programmer, not an artist. The best icon you're going to get out of me is programmer art. That said if someone wants to make a PR for a new icon I'm willing to look at it.

I think the default icon is alright, but if you want to make it look a bit modern then papirus has an icon for your program.

It's the same thing but rounded from the sides and looks a bit cleaner
![mpc-qt](https://github.com/mpc-qt/mpc-qt/assets/31146313/8523a217-b454-4c26-82f9-41a52c8cb389) ![mpc-qt](https://github.com/mpc-qt/mpc-qt/assets/31146313/0d9c6bae-c064-4965-80c3-8dc0a92b93f7) ![mpc-qt](https://github.com/mpc-qt/mpc-qt/assets/31146313/12792db6-703c-475d-8ef8-6e8e56a18aee) ![mpc-qt](https://github.com/mpc-qt/mpc-qt/assets/31146313/e9a54ed3-af2c-41cd-995d-c5b2666a9320) ![mpc-qt](https://github.com/mpc-qt/mpc-qt/assets/31146313/20023ebb-61d7-4b75-8dec-3a31224ab348) ![mpc-qt](https://github.com/mpc-qt/mpc-qt/assets/31146313/73acaf0f-f85a-4b76-b080-62966016593e)

**Comment by cmdrkotori** [comment]
Sadly papirus is gpl-v3 and the license on this repo is gpl-v2.  We'd have to move the entire repo to gpl-v3.  The best I can do is make a glance in the browser (no devtools or any such thing) and go by memory.

Here are the other icons I drew up sometime after the original icon landed in the repo.
![Screenshot_20240228_110425](https://github.com/mpc-qt/mpc-qt/assets/65291121/e5bcb7f2-e44c-41fc-9d28-dfad56987e73)

**Comment by cmdrkotori** [comment]
As requested, a rounded icon.  I think papirus has more going than that, but I can't really tell.

**Comment by ezvision** [comment]
> As requested, a rounded icon. I think papirus has more going than that, but I can't really tell.

Already looks better. The square with a ton of empty space around the smiley looked a bit out of place.

**Comment by cmdrkotori** [comment]
>What are your thoughts? I'm not a designer either but I gave it a shot in Inkscape.
I like the double one, however I think it takes too much space on the icon.

You may could also try adding a little shading to the bottom of each clapper to enhance their 3dness.

I'm no designer though.

**Comment by anwarsfaizul** [comment]
I am not an artist nor a programmer however back in Windows I was a huge fan of mpc-hc before switching to potplayer. mpc hc was a great open-source project and I thank the developer from the bottom of my heart for porting the project to Linux.
As for the icon, why not link the threads among the project's pasts and the upcoming future? like taking the original icon and modifying it to make something unique. For example, we can remove the 123 from the original icon and add something that(maybe a prop) relates to/(invokes the memory of) theatre, drama, or cinema. I believe the smiley face is too generic and reminds me of the horror/serial killer genre.

here's an example, mpc action prop+comedy/theatre logo(happy and sad face). or maybe negative film roll with popcorn
etc

**Comment by cmdrkotori** [comment]
I've put together this icon with your ideas provided above.

![theater-shadow](https://github.com/mpc-qt/mpc-qt/assets/65291121/e6b42933-43cd-4ecf-826e-e97156e20154)

**Comment by anwarsfaizul** [comment]
> I've put together this icon with your ideas provided above.

please wait I will ask around, hopefully, someone interested will take on the task....

**Comment by anwarsfaizul** [comment]
![mpc_concept](https://github.com/mpc-qt/mpc-qt/assets/3743966/c742565f-8ba5-4e32-8abd-a2510917dace)

Even I don't like it. randomly made one with paint (that's my maximum digital art skill). if someone can make something better out of it. go ahead. don't even associate me if an improved design gets selected.

**Comment by tbertels** [comment]
> I like the double one, however I think it takes too much space on the icon.
> 
> You may could also try adding a little shading to the bottom of each clapper to enhance their 3dness.

Here's a version with smaller clappers and an other one with added shadows.
Note that [Qt doesn't support drop shadows in SVGs](https://www.qtcentre.org/threads/69226-Why-they-use-png-images-icons-instead-svg-in-examples-!#post302546) so it doesn't look good with shadows.

![mpc-qt_smaller_clappers](https://github.com/user-attachments/assets/45c2224b-ee4a-4299-bb07-90dc44a26bdb)
![mpc-qt_smaller_clappers_with_shadows](https://github.com/user-attachments/assets/f575c672-815c-46fb-95dd-7173af0d6037)

**Comment by ahjolinna** [comment]
some typical modern and generic multimedia icons usually looks like this. 
These are not made by me but with AI (...like it or not) ..these are mainly for reference of what they could be...oc finding someone to make one is whole other question

PS. I personally like the 5/7 the most 

![mpc-qt 1](https://github.com/user-attachments/assets/2ae866ca-5e81-41ae-af2a-f41c51e7b7e1)
![mpc-qt 2](https://github.com/user-attachments/assets/802be16c-e05e-4f52-8158-ce69e62bd213)
![mpc-qt 3](https://github.com/user-attachments/assets/a8cdbed4-de73-426f-8843-a055c1d7ddc7)
![mpc-qt 4](https://github.com/user-attachments/assets/ce323f86-600f-47fa-9fb3-7dcaa4454458)
![mpc-qt 5](https://github.com/user-attachments/assets/2d26c30d-03e9-4d8a-a0af-64fbed63aa69)
![mpc-qt 6](https://github.com/user-attachments/assets/5017d103-d898-4f67-8ca9-bdc9eda736e5)
![mpc-qt 7](https://github.com/user-attachments/assets/4972a382-21c0-4a71-bae9-9b804f013ff9)

**Comment by cmdrkotori** [comment]
> some typical modern and generic multimedia icons usually looks like this. These are not made by me but with AI (...like it or not) ..these are mainly for reference of what they could be...oc finding someone to make one is whole other question
> 
> PS. I personally like the 5/7 the most

What these have going for them is that they have shading.  That's beyond my abilities.

**Comment by cmdrkotori** [comment]
Ok it's 5 past midnight here and I just did some tweaking of the chevrons + faint light source.  Feel free to edit.  See you in 12 or so hours.

![mpc-qt](https://github.com/user-attachments/assets/a7ebd14f-b55c-454f-afca-8843b92670b4)

**Comment by tbertels** [comment]
> Ok it's 5 past midnight here and I just did some tweaking of the chevrons + faint light source. Feel free to edit. See you in 12 or so hours.
> 
> ![mpc-qt](https://private-user-images.githubusercontent.com/65291121/384398107-a7ebd14f-b55c-454f-afca-8843b92670b4.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODEzNjAsIm5iZiI6MTczMTA4MTA2MCwicGF0aCI6Ii82NTI5MTEyMS8zODQzOTgxMDctYTdlYmQxNGYtYjU1Yy00NTRmLWFmY2EtODg0M2I5MjY3MGI0LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDE1NTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExODAxNmVlZTdiMDAzNzgzNjQxNjhlNmYwYTFkYmExMTdjOTBkZGIxNzhhMGI3ODM5MDJkMTg4ODI4MzRkZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4eu3j3xk7zsIPM8ntB9SDY5AYb5TgiW6jKo7dzwBibU)

Nice!

I think it looks pretty good apart from in the about menu where we can see the shadow of the smiley, which means that it looks rather odd with the rest flat.
So I've moved the shadows in a new layer and have disabled it. If someone can make shadows for the clappers and clappers chevrons in the future, a single click will re-enable the other shadows.
I've also removed three unused layers (there was a play image) and resized the page to content (so that the icon uses all the available space).
Finally, I've disabled the grid and changed the "Desk" color to black just for the sake of making future edits more comfortable.

![mpc-qt](https://github.com/user-attachments/assets/12036193-5937-4a6a-b656-be90fc0761b5)

**Comment by cmdrkotori** [comment]
LGTM.

@Yasand123 Do you have an email associated with your github account we can use to credit you with a `Co-authored-by:` line? I tried checking your profile but it's all private.

**Comment by tbertels** [comment]
Thank you everyone!
I think for further improvements, we'll need an actual graphic designer.
