### ISSUE TITLE
Saving Playlist crashes appimage

### ISSUE THREAD

**Issue by FTSGTK720** [mpc-qt/mpc-qt#113]
I have found an issue. I am currently using the v23.12 appimage and have found that if I right click on the playlist and select save playlist the save screen will come up and prompt me for a filename, but the app will crash when attempting to click save or cancel. The file will still get saved if save is clicked, but if cancel is clicked, then the playlist will be wiped after the app crash. Let me know if there is any more info I can get you to help out.
Thank you.

**Comment by cmdrkotori** [comment]
Works on my machine.

Can you do a backtrace?  Here's how:
```
gdb mpc-qt
run
bt full
```

**Comment by FTSGTK720** [comment]
Ok. Here is the output of the console:
`Starting program: /home/***/***/mpc-qt-linux-x64-2312.AppImage 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Detaching after fork from child process 9568]
process 9565 is executing new program: /usr/bin/env
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
process 9565 is executing new program: /usr/bin/bash
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Detaching after fork from child process 9574]
process 9565 is executing new program: /tmp/.mount_mpc-qt4V8U4O/usr/bin/mpc-qt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe76006c0 (LWP 9576)]
QApplication: invalid style override 'gtk' passed, ignoring it.
	Available styles: Windows, Fusion
[New Thread 0x7fffe6c006c0 (LWP 9577)]
[New Thread 0x7fffe62006c0 (LWP 9578)]
[New Thread 0x7fffe58006c0 (LWP 9579)]
[New Thread 0x7fffe4e006c0 (LWP 9580)]
[New Thread 0x7fffdfe006c0 (LWP 9581)]
[New Thread 0x7fffdf4006c0 (LWP 9582)]
[New Thread 0x7fffdea006c0 (LWP 9583)]
[New Thread 0x7fffde0006c0 (LWP 9584)]
[New Thread 0x7fffdd6006c0 (LWP 9585)]
[Thread 0x7fffde0006c0 (LWP 9584) exited]
[New Thread 0x7fffde0006c0 (LWP 9586)]
[New Thread 0x7fffa7e006c0 (LWP 9587)]
[New Thread 0x7fffa50006c0 (LWP 9588)]
[New Thread 0x7fff97e006c0 (LWP 9589)]
[New Thread 0x7fff974006c0 (LWP 9590)]
[New Thread 0x7fff96a006c0 (LWP 9591)]
[New Thread 0x7fff960006c0 (LWP 9592)]
[New Thread 0x7fff956006c0 (LWP 9593)]
[New Thread 0x7fff94c006c0 (LWP 9594)]
[New Thread 0x7fff8be006c0 (LWP 9595)]
[New Thread 0x7fff8b4006c0 (LWP 9596)]
[New Thread 0x7fff8aa006c0 (LWP 9597)]
[New Thread 0x7fff8a0006c0 (LWP 9598)]
[New Thread 0x7fff896006c0 (LWP 9599)]
Cannot load libcuda.so.1
[New Thread 0x7fff88c006c0 (LWP 9600)]
[New Thread 0x7fff7fe006c0 (LWP 9601)]
[New Thread 0x7fff7f4006c0 (LWP 9602)]
[Detaching after fork from child process 9603]
[Detaching after fork from child process 9604]
[Detaching after fork from child process 9605]
[Detaching after fork from child process 9606]
[Detaching after fork from child process 9607]
[Detaching after fork from child process 9608]
[Detaching after fork from child process 9609]
[Detaching after fork from child process 9610]
[Detaching after fork from child process 9611]
[Detaching after fork from child process 9612]
[Detaching after fork from child process 9613]
[New Thread 0x7fff7ea006c0 (LWP 9614)]
[New Thread 0x7fff7e0006c0 (LWP 9617)]
[New Thread 0x7fff7d2006c0 (LWP 9618)]
[New Thread 0x7fff73e006c0 (LWP 9619)]
[New Thread 0x7fff734006c0 (LWP 9620)]
[New Thread 0x7fff72a006c0 (LWP 9626)]
[Thread 0x7fff72a006c0 (LWP 9626) exited]
malloc(): unaligned fastbin chunk detected

Thread 2 "QXcbEventQueue" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe76006c0 (LWP 9576)]
0x00007ffff5eab32c in ?? () from /usr/lib/libc.so.6
(gdb) bt full
#0  0x00007ffff5eab32c in ?? () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff5e5a6c8 in raise () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00007ffff5e424b8 in abort () from /usr/lib/libc.so.6
No symbol table info available.
#3  0x00007ffff5e43395 in ?? () from /usr/lib/libc.so.6
No symbol table info available.
#4  0x00007ffff5eb52a7 in ?? () from /usr/lib/libc.so.6
No symbol table info available.
#5  0x00007ffff5eb88cc in ?? () from /usr/lib/libc.so.6
No symbol table info available.
#6  0x00007ffff5eb97ed in malloc () from /usr/lib/libc.so.6
No symbol table info available.
#7  0x00007fffebf17e2f in ?? () from /usr/lib/libxcb.so.1
No symbol table info available.
#8  0x00007fffebf1838f in ?? () from /usr/lib/libxcb.so.1
No symbol table info available.
#9  0x00007fffebf19e1d in xcb_wait_for_event () from /usr/lib/libxcb.so.1
No symbol table info available.
#10 0x00007fffe77b4208 in ?? ()
   from /tmp/.mount_mpc-qt4V8U4O/usr/plugins/platforms/../../lib/libQt6XcbQpa.so.6
--Type <RET> for more, q to quit, c to continue without paging--
No symbol table info available.
#11 0x00007ffff66bdfcf in ?? ()
   from /tmp/.mount_mpc-qt4V8U4O/usr/bin/../lib/libQt6Core.so.6
No symbol table info available.
#12 0x00007ffff5ea955a in ?? () from /usr/lib/libc.so.6
No symbol table info available.
#13 0x00007ffff5f26a3c in ?? () from /usr/lib/libc.so.6
No symbol table info available.
(gdb) `
