### ISSUE TITLE
Lua script

### ISSUE THREAD

**Issue by IM71** [mpc-qt/mpc-qt#114]
Hi, how can I use lua script in mpc-qt?
I tried add a script folder in APPDATA\mpc-qt, but the script didn't seemed to be working. (the script I tried was thumbfast)

Was there anything I did wrong?

Thanks

**Comment by cmdrkotori** [comment]
Scripts aren't really supported.   IIRC they load but there's no real way for the frontend to communicate with them that's not hardcoded.  And even then it doesn't always work.

You're better off making a feature request for the program to include the script's features natively.
