### ISSUE TITLE
Feature Request: Custom jump distances

### ISSUE THREAD

**Issue by frazarshad** [mpc-qt/mpc-qt#117]
Add the ability to add custom jump distance
![image](https://github.com/mpc-qt/mpc-qt/assets/8860764/c4623347-526c-44db-a96c-b2fdf31a7f61)

**Comment by cmdrkotori** [comment]
These are actually in a different spot.  Although I suppose they could be moved to the tweaks page to match the latest version of mpc-hc.

![Screenshot_20240521_182608](https://github.com/mpc-qt/mpc-qt/assets/65291121/ce765cae-69a4-448e-bceb-95fcc51aa1c4)

**Comment by cmdrkotori** [comment]
Ah right, that screenshot is from mpc-be, which is why it shows those settings under miscellaneous instead of tweaks.  That's fine too I guess.

Speaking of, I forgot that we did copy the interface from mpc-be in certain places where mpc-hc was lacking, such as where to put the audio settings.  So that setting placement is quite valid indeed.

**Comment by tbertels** [comment]
> Speaking of, I forgot that we did copy the interface from mpc-be in certain places where mpc-hc was lacking, such as where to put the audio settings. So that setting placement is quite valid indeed.

I'm not sure if you mean that Playback is the right place for it, but I do.
I've seen [someone not finding the mpc-hc setting in tweaks](https://forum.videohelp.com/threads/399956-mpc-hc-jumping-to-next-file-disabling-chapters#post2604323).

About the number of jump distances, do people really use three jump distances?

I wonder if the problem isn't that the "Time step" (called "large step" in the code) is used by default (left and right keys) and set to 5 seconds while the "fine" step (called small step in the code) is triggered with the Shift modifier and set to 1 second by default.
Maybe these would fix it:
* renaming the "Time step" to "normal step", setting it to 2500 ms and triggering it without a modifier.
* and renaming the "fine step" to "large step", setting it to 20 seconds and triggering it with a modifier (I use Alt but maybe Shift could be kept).

**Comment by cmdrkotori** [comment]
> > Speaking of, I forgot that we did copy the interface from mpc-be in certain places where mpc-hc was lacking, such as where to put the audio settings. So that setting placement is quite valid indeed.
> 
> I'm not sure if you mean that Playback is the right place for it, but I do. I've seen [someone not finding the mpc-hc setting in tweaks](https://forum.videohelp.com/threads/399956-mpc-hc-jumping-to-next-file-disabling-chapters#post2604323).

Yeah it is a good place at the moment, and I'd try to keep it there if at all possible.  However, both mpc-hc and notably mpc-be now have them under the tweaks/misc page respectively.

>About the number of jump distances, do people really use three jump distances?

I agree with you, and I certainly don't use them, but to some extent we're limited by what MPC-HC (and MPC-BE) decides to do.  Back when I made this program, mpc-hc didn't have large jump distances.

clsid2's fork of MPC-HC now has this as default
* Left/Right: normal jump distances of 5000ms
* Shift+Left/Shift+Right: small jump distances of 1000ms
* Ctrl+Left/Ctrl+Right: frame step
* Ctrl+WheelUp/Ctrl+WheelDown: large jump distances of 20000ms

I just installed the latest version mpc-hc under wine and jumping back and forth with the scroll wheel is I feel something that one could get used to.  Perhaps the best thing to do here is to add large jumps and put the option somewhere, though I'm open to suggestions.

> I wonder if the problem isn't that the "Time step" (called "large step" in the code) is used by default (left and right keys) and set to 5 seconds while the "fine" step (called small step in the code) is triggered with the Shift modifier and set to 1 second by default. Maybe these would fix it:
> 
> * renaming the "Time step" to "normal step", setting it to 2500 ms and triggering it without a modifier.
> 
> * and renaming the "fine step" to "large step", setting it to 20 seconds and triggering it with a modifier (I use Alt but maybe Shift could be kept).

Yes, good idea.  Although it might be simpler to add a large step without changing the existing code.

However, I've noticed that if we add a third option on this page we may have do a small redesign of that page to fit the new options while keeping the dialog less than 768px high-- perhaps we could remove the text about floating window managers, maybe stagger the columns a bit, and move "After Playback" to the right hand side.  This is a bit of a headache, and it would look messy.  So perhaps changing the meaning of these two options is a good idea.  However I don't want to let gui get in the way of functionality.

**Comment by tbertels** [comment]
> However, I've noticed that if we add a third option on this page we may have do a small redesign of that page to fit the new options while keeping the dialog less than 768px high-- perhaps we could remove the text about floating window managers, maybe stagger the columns a bit, and move "After Playback" to the right hand side. This is a bit of a headache, and it would look messy. So perhaps changing the meaning of these two options is a good idea. However I don't want to let gui get in the way of functionality.

We could also do it like MPC-HC : the three options on the same line and one line for the explanation (with or without the default button):

![nSh1j](https://github.com/user-attachments/assets/27716f27-f886-443f-83ac-84e6e68010fa)

But maybe align each explanation above their related value if that's feasible.

By the way, there should be a space between the units and the values.
