### ISSUE TITLE
Latest version not launching on fedora 40

### ISSUE THREAD

**Issue by ezvision** [mpc-qt/mpc-qt#120]
I get this error when trying to launch the latest version after updating my system: 
mpc-qt: symbol lookup error: mpc-qt: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6

any idea what could be causing this?

**Comment by cmdrkotori** [comment]
Run a `make clean` in the folder where you compiled mpc-qt, and rebuild the project.
