### ISSUE TITLE
Dolby Digital Plus and Dolby TrueHD/Atmos passthrough

### ISSUE THREAD

**Issue by 41HT** [mpc-qt/mpc-qt#123]
Please consider adding support for Dolby Digital Plus (EAC3) and Dolby TrueHD/Atmos audio passthrough. Right now MPC-QT seems to support only AC3, DTS and DTS-HD. I'm not sure if there's an option to enable EAC3 and TrueHD/Atmos passthrough, but if there is, please guide me. Thank you.

**Comment by cmdrkotori** [comment]
Actual libmpv supported spdif codecs are `ac3`, `dts`, `dts-hd`, `eac3`, `truehd` or any combination (comma separated) thereof.  Use those until the next release when the default (provided by the placeholder text) is updated.
