### ISSUE TITLE
Is there a way to change the audio language priority? 

### ISSUE THREAD

**Issue by shoui520** [mpc-qt/mpc-qt#127]
In MPC-HC, you can change your preferred audio language for video files that have multiple audio tracks (for example, a track for Japanese audio and a track for an English dub). This option can be changed by listing your preferred language(s) in the "Audio" section in the options. 
You can replicate this behaviour in MPV by editing mpv.conf, is there anyway to pass an mpv.conf to mpc-qt or change the preferred audio track in a different way?

**Comment by cmdrkotori** [comment]
This would be done by the settings dialog I guess.

At present the player is geared for binge watching entire seasons, (my use case,) and comes from a time before there was a settings dialog.  The idea was that you manually select custom audio / sub tracks on the first episode, and the program will look for the identical track in subsequent files.

I guess this logic could be improved to auto select a specific track if it can't find a default sub track (selected by the file) or a custom track (selected by you).

I doubt I have any files to test this on though.  If you have a sample of such files, feel free to provide one.

**Comment by cmdrkotori** [comment]
Fixed in master.
