### ISSUE TITLE
Would you consider building AppImage in Ubuntu 20.04?

### ISSUE THREAD

**Issue by stdedos** [mpc-qt/mpc-qt#128]
One tiny issue with the AppImages is that their C library is "bound" to the system that they are built against:

```console
...
/tmp/.mount_mpc-qt8DtwPY/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_mpc-qt8DtwPY/usr/bin/../lib/libpulsecommon-15.99.so)
/tmp/.mount_mpc-qt8DtwPY/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_mpc-qt8DtwPY/usr/bin/../lib/libpulsecommon-15.99.so)
/tmp/.mount_mpc-qt8DtwPY/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_mpc-qt8DtwPY/usr/bin/../lib/libdecor-0.so.0)
/tmp/.mount_mpc-qt8DtwPY/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_mpc-qt8DtwPY/usr/bin/../lib/libkrb5.so.3)
...
$ ldd --version ldd
ldd (Ubuntu GLIBC 2.31-0ubuntu9.15) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

I haven't found you calling https://github.com/mpc-qt/mpc-qt/blob/master/make-release-linux.sh on the CI, so, I assume you build manually/locally? (I guess that makes it harder to build against multiple systems :sweat_smile: )

**Comment by cmdrkotori** [comment]
>Would you consider building AppImage in Ubuntu 20.04?

No. There are no Qt6 packages on 20.04.  There is also the matter that [Qt6 is not supported on 20.04](https://doc.qt.io/qt-6/linux.html).

fwiw, the last Qt 5 version was commit df7942655b1ba645a4cc2b14a1a739d655cc44d8.  You can try building that on your system.

Anyway you really should upgrade your system.  **You are missing out** on improved hardware support, bug fixes, and features added in newer software.  **Simply put, it's not in your own interest to be running Ubuntu 20.04.**

So with all that in mind, I will not be supporting it.

>I haven't found you calling https://github.com/mpc-qt/mpc-qt/blob/master/make-release-linux.sh on the CI, so, I assume you build manually/locally?

Yes I build releases manually, both for Linux and Windows.  The Linux CI is to catch build errors on older systems, so I don't make any artifacts for it.

>(I guess that makes it harder to build against multiple systems 😅 )

Not really.  My dependencies are libmpv and Qt, and their API do not change much if at all.  The API of a particular library version is the same even if it's a different distro.  And with mpv you can tell it to observe/modify a property that was added in a later version and it will simply ignore it.

And besides, if you have the appropriate packages (libmpv and qt6 dev) installed, you too can run `./make-release-linux.sh` on your own system.  It'll do it all for you; everything that comes after installing packages on your system... I guess I should put this in the README.

**Comment by cmdrkotori** [comment]
It took me all day to do this. https://files.catbox.moe/je9whh.AppImage

Note that the build environment is hacked together so some build dependency is likely missing, so caveat emptor.  Although it seems to play HEVC and AV1 fine from my quick test.

**Comment by cmdrkotori** [comment]
Here's the set of build instructions for Ubuntu 20.04 if my log is correct.

```
sudo apt install build-essential
sudo add-apt-repository ppa:savoury1/build-tools
sudo add-apt-repository ppa:savoury1/qt-6-2
sudo add-apt-repository ppa:savoury1/llvm-defaults-13
sudo add-apt-repository ppa:savoury1/graphics
sudo add-apt-repository ppa:savoury1/display
sudo add-apt-repository ppa:savoury1/multimedia
sudo apt upgrade
sudo apt dist-upgrade
sudo apt install qmake6 qt6-base-dev qt6-l10n-tools libqt6svg6-dev
sudo apt install git devscripts equivs
git clone https://github.com/mpv-player/mpv-build.git
cd mpv-build
./update
printf "%s\n" -Dlibmpv=true > mpv_options
cp debian/changelog.TEMPLATE debian/changelog
mk-build-deps -s sudo -i
dpkg-buildpackage -uc -us -b -j4
sudo dpkg -i ../mpv_2024.05.24.2fa66b850d_amd64.deb
cd ~
git clone https://github.com/mpc-qt/mpc-qt
cd mpc-qt
kate mpc-qt.pro  # Replace !win32:PKGCONFIG += mpv with !win32:LIBS += -lmpv
./make-release-linux.sh
```

**Comment by stdedos** [comment]
I am ... very happily surprised you decided to do it after all, **despite** your passionate speech about always-updating. And qt-6 none-the-less!

I was already happy with the https://github.com/mpc-qt/mpc-qt/commit/df7942655b1ba645a4cc2b14a1a739d655cc44d8 hint

I couldn't find a "Donate" option. You are my OSS hero of the year.

**Comment by cmdrkotori** [comment]
You'll be happy to know that the latest release was made on 20.04.
