### ISSUE TITLE
native script support

### ISSUE THREAD

**Issue by Astolfo2001** [mpc-qt/mpc-qt#130]
with the many mpv user scripts that exist on the internet: https://github.com/stax76/awesome-mpv

so why not? if you just added in native user script support, then this video player would be a must download for me

**Comment by cmdrkotori** [comment]
On lines 119-133 of mpvwidget.cpp we pass the `$MPC_CONFIG/scripts` folder to mpv
```c++
    // Fetch installed scripts
    QString scriptPath = Storage::fetchConfigPath() + "/scripts";
    auto scriptInfoList = QDir(scriptPath).entryInfoList({"*.lua"}, QDir::Files);
    QStringList scripts;
    for (auto &info : scriptInfoList)
        scripts.append(info.absoluteFilePath());

    // Initialize mpv playback instance
    MpvController::OptionList earlyOptions = {
        { "vo", "libmpv" },
        { "ytdl", "yes" },
        { "audio-client-name", clientName },
        { "load-scripts", true },
        { "scripts", scripts }
    };
```

On Linux this is `~/.config/mpc-qt/scripts`, on Windows it is `%APPDATA%\Roaming\mpc-qt\scripts`.

However we do not forward key or mouse events to mpv, so there is no way to interact with said scripts.

Hope that clears it up for you.

**Comment by cmdrkotori** [comment]
Optionally sending mouse and key events was just implemented in master.

**Comment by Astolfo2001** [comment]
> Optionally sending mouse and key events was just implemented in master.

how do I turn that feature on when compiling?

**Comment by cmdrkotori** [comment]
It's a run-time option under the tweaks page in the settings.

![Screenshot_20240529_102618](https://github.com/mpc-qt/mpc-qt/assets/65291121/51abcb03-6091-46e2-ba96-498c98bf8543)
