### ISSUE TITLE
need help compiling in MSYS2

### ISSUE THREAD

**Issue by Astolfo2001** [mpc-qt/mpc-qt#131]
Hi
From what I could tell, it seems like I did everything correctly
However when I type "qmake6 ENABLE_LOCAL_MPV=1 mpc-qt.pro" and hit enter, it gives me these errors instead of actually compiling the program like it's supposed to
![compil error 1](https://github.com/mpc-qt/mpc-qt/assets/135289980/318a33fb-1bfa-4167-9884-dd5c9490a1f2)
![compil error 2](https://github.com/mpc-qt/mpc-qt/assets/135289980/b040c230-4f21-4c0b-9265-f820ae450802)

The OS I am on is Windows 11 64-bit btw.

So, how do I fix it so I can compile the program properly?

**Comment by cmdrkotori** [comment]
That's exactly the same place it sometimes fails in the CI too.  It's related to generating the windows icon from the svg file.  Try running `./make-win-icon.sh` and having another go.

Note that if you want to build against MSYS2 mpv, there's no need for ENABLE_LOCAL_MPV=1.

**Comment by cmdrkotori** [comment]
Post updated with more instructions.

**Comment by cmdrkotori** [comment]
Closing as the question has been answered.
