### ISSUE TITLE
Please make 32 bits version for Windows 7 OS

### ISSUE THREAD

**Issue by trimechee** [mpc-qt/mpc-qt#133]
Hello, Our beloved Mpc-qt is the most powerful media player in the world, thank you so much for this awesome amazing media player! 💯 🥇

Recently my laptop broke down and I went back to using my old laptop made in 2012 which has windows 7 os 32 bits, I was hoping to use our beloved Mpc-qt because streaming videos freeze lag on the heavy web browser but apparently there is no 32-bit version for windows 7 of Mpc-qt and we hope please there will be a version of GridPlayer for windws 7 os 32 bts, please, because surely, millions of people still have machines with the legendary windows 7 os and the old machines are robust and still work and the Mpc-qt  is useful to save these machines from destruction, thank you very much !

(maybe it can help it seems there is 32 bits for open source mpc-be , and also smplayer has 32 bits version.....)

https://www.softpedia.com/get/Multimedia/Video/Video-Players/MPC-BE.shtml )

**Comment by cmdrkotori** [comment]
Qt 6 (our gui dependency) doesn't support Windows 7.

Chances are your old machine supports 64bits, it simply has a 32bit operating system installed.  I'd try installing Windows 10 64bit over the top of it.

**Comment by trimechee** [comment]
Hello Mr @cmdrkotori , i find these softwares, they add support of mpc qt and  they say we can use mpc qt in windows 7 os ! 

https://github.com/commandcontrolQ/VxKex?tab=readme-ov-file#faq

https://github.com/commandcontrolQ/VxKex

https://github.com/i486/VxKex
