### ISSUE TITLE
Hey Dude please use Github Actions to build binaries for Windows

### ISSUE THREAD

**Issue by SonaliBendre** [mpc-qt/mpc-qt#14]
Yes it will build server-side, you don't have to sacrifice your pc

**Comment by cmdrkotori** [comment]
Patches welcome.

**Comment by SonaliBendre** [comment]
> Patches welcome.

Give me instruction how to build it for Windows. 
BTW We want mpc-qt for windows and you don't provide binary for windows. Please provide a build script for windows or guide how to build I'll write workflow for Actions
Thanks

**Comment by cmdrkotori** [comment]
I provide binaries for Windows on the release page. Once the MSYS2 environment is set up as described in the README's Windows section, I create a zip-file using the make-release-win script, with the caveat that the copied dlls need to be manually updated with each new version of them, so you may want to use `windeployqt` in the build server instead. Apart from that compiling this on Windows is practically identical to compiling it on Linux.

**Comment by zhongfly** [comment]
Maybe a little late, I recently had time to follow the README to complete this work.
Just enter the download links of libmpv and yt-dlp to start compiling

https://github.com/zhongfly/Action-Build/blob/7c74a20fc817f645ac8a8441794a8f7821825422/.github/workflows/mpc-qt.yml#L4-L11

**Comment by cmdrkotori** [comment]
We now have a basic github action running, but it's for Linux.
I think what we'll be doing for Windows is using the mpv/yt-dlp bundled with msys2 and copying all of their dlls into the zip. We won't have to download external dependencies that way, because everything can be gotten from the build server.

**Comment by cmdrkotori** [comment]
Done. If you want to get yt-dlp/youtube-dl streaming working, you'll have to download that yourself and add it to the executable folder.
