### ISSUE TITLE
Video black flickering

### ISSUE THREAD

**Issue by mysteryx93** [mpc-qt/mpc-qt#16]
Just installed MPC-QT on Garuda Linux (Arch). With default settings, videos flicker with black frames. What information would you need to solve this? I'm using NVIDIA graphics.

**Comment by cmdrkotori** [comment]
What's your wm? Can you disable compositing? Try using some of the video presets and see if that changes anything.

**Comment by LDEVDEV** [comment]
Hello, 

I have same experience on Endeavouros (Arch) and disabling compositing (xfwm4) did not help. 

When is “Dumb mode“ on in Options/Playback/Output/ there is no black flickering in windowed playback but unfortunately it persists in fullscreen mode. I tried various settings in playback options but nothing worked.

**Comment by frazarshad** [comment]
Hello, 
I'm getting the same issue on my setup (os: Arch, wm: i3, compositor: picom).
I can solve the issue temporarily by using dumb mode and turning on my compositor.
with the compositor disabled, the flickering seems to be greater.

**Comment by Mark42XLII** [comment]
Similar issue here. Arch Linux, Awesome as WM, picom as the compositor, Intel iGPU.
mpv works fine, but mpc-qt flickers with black frames. The only workaround I found over here was Dumb Mode without compositing (works even on fullscreen).
Furthermore, VBR videos stutter with mpv and cause even worse black flickering on mpc-qt, this time unfixable with just Dumb Mode and compositing off.

**Comment by uhhmeeyell** [comment]
Same issue here with black frame flickering. I am also using an Intel iGPU while "Dumb" mode doesn't help at all. I'm running on Solux Budgie (5.14.21-210.current).

**Comment by cmdrkotori** [comment]
This is probably a bug in mpv since putting it into dumb-mode seems to fix the issue.

**Comment by LDEVDEV** [comment]
Update to newly released Mesa 21.3.5 fixed this black flickering for me.

**Comment by cmdrkotori** [comment]
I'm closing this now because this was an upstream bug.
