### ISSUE TITLE
Minimizing during playback causes a segfault

### ISSUE THREAD

**Issue by Yasand123** [mpc-qt/mpc-qt#160]
If I minimize the window to the taskbar while a video is playing I get a segfault. This does not happen if I pause first. I sadly cannot tell when this started happening because it's been a while since I got back on Linux. I tried the pre-built binaries and compiling from source, both have the same behavior.

Current set-up (everything is up-to-date):
- Arch Linux 6.10.8
- KDE Plasma 6.1.4
- Nvidia driver 560.35.03
- Wayland

**Comment by cmdrkotori** [comment]
Works on my machine.

Please run mpc-qt through gdb and post a backtrace with `bt full`.

**Comment by cmdrkotori** [comment]
This crash is in the nvidia driver.  I can't fix bugs in that.  In any case you may have some luck by enabling the wayland codepath by turning this option on, as I see that the app is using XWayland.

![Screenshot_20240908_152647](https://github.com/user-attachments/assets/9a5fa630-e8e3-4c09-a04b-9e8bc8a9e397)
