### ISSUE TITLE
MPC-QT dont play top/first recent file or streaming media after stop

### ISSUE THREAD

**Issue by denzveloper** [mpc-qt/mpc-qt#161]
MPC-QT dont Play first list recently file after i press stop button that media. Is play, but they played second list of recent file. Whatever the file is a streaming or offline media, it's still the same.

can fix that? after stop then play last of recent file?

Screen record is here:

https://github.com/user-attachments/assets/e0e74349-7b53-4073-a861-81b59272e057

or:
https://drive.google.com/file/d/1dQlmwuOt-SA5HUrk-s5k5jDBr2deLuD-/view?usp=sharing

Specs:
- OS: openSUSE Tumbleweed 20240904 x86_64 
- DE: Plasma 6.1.4 
- CPU: AMD Ryzen 5 PRO 3500U
- mpc-qt Version 24.06 w/  Qt version 6.7.2.

**Comment by tbertels** [comment]
Thanks for the report!
This should be fixed by https://github.com/mpc-qt/mpc-qt/pull/163

**Comment by denzveloper** [comment]
ok thank you!
