### ISSUE TITLE
With a dark system theme, everything looks great except the seek bar's seek handle

### ISSUE THREAD

**Issue by AlexFolland** [mpc-qt/mpc-qt#20]
**To reproduce:**

1. Use a dark system Qt5 and Qt6 theme on Linux.
2. In the mpc-qt "Interface" settings, set "Theme" to "System (Linux only)".
3. In the mpc-qt "Interface" settings, set "Fallback" to "White (for black palette)".
4. In the mpc-qt "Stylesheet" settings, set "Use Qt's inbuilt fusion style (may require restart)" to false.
5. In the mpc-qt "Stylesheet" settings, blank the "Application Stylesheet" multi-line text field.
6. Save all settings and restart mpc-qt.
7. Play a 2-to-4-hour video.
8. Try to find the seek handle on the seek bar.

**Observed behavior:**

With a dark system theme, everything looks great except the seek bar's seek handle, as pointed out in the following modified screenshot:

![image](https://user-images.githubusercontent.com/601517/153968794-ef7cd7b5-a34e-4dee-94fa-39cf7ef8b43c.png)

The seek handle is barely visible due to its extremely low contrast against the seek bar.  Finding it quickly while the video is playing is difficult.

**Expected behavior:**

The seek handle is expected to have a high contrast against the background to allow finding it on the seek bar quickly.  If it was white in a dark theme, it would work better than this.  I'm not sure what exact change to the program could accomplish this.

**Comment by AlexFolland** [comment]
Thank you for your change!  I've tried a build from the latest git HEAD commit now.  Here's a screenshot from that build.

![image](https://user-images.githubusercontent.com/601517/153992598-b81dcab6-2089-45cf-8c09-7f322f46d39b.png)

The seek bar handle does look different from how it did previously, but it is still dark, unlike the play, pause, and stop icons, which are nice and bright.  Therefore, I'm requesting this be reopened.

**Comment by cmdrkotori** [comment]
What theme are you using?

**Comment by cmdrkotori** [comment]
Try git head now and turn this setting on:
![Screenshot_20220216_100206](https://user-images.githubusercontent.com/65291121/154170575-dc551c75-8d27-4aa6-98e4-8007edca3601.png)

**Comment by AlexFolland** [comment]
That looks like this.

![image](https://user-images.githubusercontent.com/601517/154194833-225fc3a8-ce68-4394-8785-2d38803ece3c.png)

This is a lot better!  The issue is no longer nearly as severe.  My only nit to pick left is that the seek bar itself is the same color as the seek handle, when the seek bar could have been left at the original color.  The only part that needs to be bright is the seek bar's seek handle.  It's a little bit ugly this way, but much better than the low-contrast original.  Thank you very much for the fixes!

As for which theme I'm using, it's `QT_QPA_PLATFORMTHEME` set to `qt5gtk2` and with qt5gtk2 and qt6gtk2 installed, with the matcha-dark-azul gtk theme.  In case you're curious about my rationale, this is so that GTK and Qt programs can look the same instead of wildly and uncontrollably different.  It works great for my needs and I use several Qt programs this way, like qbittorrent, qmmp, mumble, and ksysguard.  Slider controls are usually blue with a white handle, so the mpc-qt seek bar is a bit unusual.  Here's an example from qmmp which is also affected by my theme.  You can see the seek bar and volume bar at the bottom with the expected widget style.

![image](https://user-images.githubusercontent.com/601517/154195758-966d332c-cef1-4c57-9610-e3541a8e6491.png)

My personal ideal fix would be to use the slider control from my theme, which looks excellent.  That being said, I realize you and other authors of mpc-qt are aiming more toward trying to mimic the MPC-HC style, so I do understand that.
