### ISSUE TITLE
More of a question

### ISSUE THREAD

**Issue by asianmusicguy** [mpc-qt/mpc-qt#25]
@cmdrkotori  this id more of a question I remember looking at this a number of years ago and thinking it was not active am I recalling wrong ? also with that said im currently settling for mpv.net is this in a workable state to be able to replace it?

**Comment by cmdrkotori** [comment]
It's less active than what it was in 2015-2018 now that all the low-hanging-fruit has been picked. But I still am working on improving it; see for example #19 and a646836280da236e8cc3a13052d68ece6076e0cb.

It's in a workable enough state that I use it as a daily driver. YMMV.
