### ISSUE TITLE
Timeline slider isn't vertically centered on timeline

### ISSUE THREAD

**Issue by tbertels** [mpc-qt/mpc-qt#256]
Regression caused by be267c475ebe8f41c6e0e6414cdaa5399c521b24.

Before:

![Copie d'écran_20241111_155718](https://github.com/user-attachments/assets/2004e6d8-0ea9-4930-8953-2f50f3e4bc64)

Now:

![Copie d'écran_20241110_135607](https://github.com/user-attachments/assets/5c1eeb6e-4c43-43b8-9257-df1c0454e26e)

**Comment by cmdrkotori** [comment]
Yep, only affect Hi-DPI displays
`env QT_SCALE_FACTOR=2 mpc-qt` reproduces this bug.
