### ISSUE TITLE
Doesn't play sound

### ISSUE THREAD

**Issue by RomanSh-shell** [mpc-qt/mpc-qt#267]
Crushes DTS and DD tracks in .mkv files

**Comment by tbertels** [comment]
I'm guessing you've tested it with an other media player?

If you only have this problem with mpc-qt, you can enable the log file (in Options > Logging), reproduce the problem, close mpc-qt then attach the log file here.

**Comment by RomanSh-shell** [comment]
[mpc-qt-log.txt](https://github.com/user-attachments/files/17815805/mpc-qt-log.txt)

**Comment by tbertels** [comment]
I don't see anything special in the log.
By the way, did you redact it? It seems to miss the first seconds.

Can other media players play that file with sound?

**Comment by RomanSh-shell** [comment]
Yes. I'd open that file in vlc, but sound not played, and in mpc-hc, and it played normally

**Comment by RomanSh-shell** [comment]
Ok. Thank you!

**Comment by tbertels** [comment]
Were you able to fix the problem?
