### ISSUE TITLE
Hardware decoding does not work across multiple codecs using the AppImage

### ISSUE THREAD

**Issue by n3thshan** [mpc-qt/mpc-qt#282]
### Description 
I tried playing h264, vp9 and av1 videos and none of them appear to be hardware decoded even after enabling the option in settings. 

### Steps to reproduce
1. Go to View > Settings > Hw. decoding > Tick Use hardware-accelerated decoding 
2. Under Hardware decoding backend try both auto detect and VAAPI (because im on intel arc integrated) 
3. Optionally under Codecs to allow hardware decoding, tick All

### Observed result 
![image](https://github.com/user-attachments/assets/6afaad87-a59e-487b-8d27-31322eda8ee9)

### Expected result 
The video decode usage should show above 0% 

### Additional information

- Distro: Aurora 41 from Universal blue (similar to Fedora Kinoite but with codecs pre-installed using the negativo17 repo) 
- Graphics: Intel Arc Meteor Lake integrated 
- Tested on Haruna flatpak and it works fine there

**Comment by n3thshan** [comment]
hi! great to hear that its fixed! i will try it next month then assuming that u will release it on the 1st itself. Also the Application Messages setting is enabled but i dont see any message anywhere. is there a keybind to activate the OSD?

**Comment by tbertels** [comment]
The release will surely happen in early December though no promises on the 1st.

I meant the "General Statistics" setting. 
By default, you can press Ctrl+J to cycle between OSD modes, the shortcut should be visible in the menu.

**Comment by tbertels** [comment]
The version 24.12 is released, so you can test it. 😉
