### ISSUE TITLE
pipewire support?

### ISSUE THREAD

**Issue by ahjolinna** [mpc-qt/mpc-qt#29]
as mpv has added pipewire support and it seems to be the future for linux (away from pulse) ....I was wondering is there any settings and/or tweaks that could be added to mpc-qt?

PS. I'm not sure yet but it seems when I manually choose my audio output to [pipewire] mpc-qt wont work/play any videos, it will even crash

**Comment by cmdrkotori** [comment]
IIRC we simply populate the dialog with the contents of audio-device-list. Of course, if there are any pipewire sub-options, those haven't been added yet.

I'm limited to testing for this on Fridays, because I have Zoom meetings the rest of the week, and Zoom doesn't like pipewire's pulseaudio emulation layer just yet.

**Comment by ahjolinna** [comment]
I'm no pipewire expert as I haven't bother to look into any tweaks and stuff like I did with pulse (I havent even bother to look into WirePlumber yet) ...

anyway, one thing that bother me was that when I did choose pipewire manually mpc-qt wouldn't work


PS. I thought the zoom issue for pipwewire was resolved, maybe I miss remember ...then again I dont use zoom at all...only once (thank god)

**Comment by ahjolinna** [comment]
have you revisited pipewire? (has your zoom issue been resolved), as some big distros are already using it, like SteamOS (on SteamDeck), Fedora 34+ and openSUSE tumbleweed ..at least and Ubuntu will start to use it with version 22.10

**Comment by cmdrkotori** [comment]
Yeah zoom seems to have fixed itself but curiously though it is keeping me on xorg. I switched myself to pipewire about a month ago and all seems to be good here. In any case, issue is fixed.

**Comment by ahjolinna** [comment]
thanks, love you @cmdrkotori  ...no homo, okay maybe little :D

**Comment by cmdrkotori** [comment]
Ok, please ignore that last notification (if you got it); I referenced the wrong issue in a commit.
