### ISSUE TITLE
Player resizes after each track change

### ISSUE THREAD

**Issue by TwoLeaves** [mpc-qt/mpc-qt#3]
Whenever the next track plays, the mpc-qt window resizes based on the cover art size (I use the program only for music). So if I shrink or enlarge the player it reverts again on every track change. Is it possible to disable this resizing, or else remove the video (or cover art) display entirely? Perhaps an option under View -> Video.

I was going to give it a go by tinkering with the MpvGlWidget code (?), but didn't have the heart to go through the Windows compilation process.

Thanks.

**Comment by cmdrkotori** [comment]
View->Zoom->Disable Snapping (Alt+0)
