### ISSUE TITLE
quick playlist broken (at least on 4k)

### ISSUE THREAD

**Issue by ahjolinna** [mpc-qt/mpc-qt#30]
is it just me or has the quick playlist been broke for a while at least on 4k screen? I just see just two colors (base and hover one) , I dont see any txt, I can only see the text if I have 1 or 2 things in the playlist 

![image](https://user-images.githubusercontent.com/6993072/156169218-fafa9871-0ac5-490d-a57c-41162eed9318.png)

![image](https://user-images.githubusercontent.com/6993072/156164150-e52251a7-eac6-4230-9c99-895fab167bc3.png)

**Comment by ahjolinna** [comment]
was this a Qt5 bug? :D as now after I update my openSUSE that included some qt pkgs everything is fine :D

(I only see [qt5-qtbase](https://build.opensuse.org/request/show/958066) being updated, which causes few qt5 pkgs being rebuild)

kinda amusing, as I have had this issue for a long time, and now it got fixed :D by happenstance with next openSUSE update :D 

![image](https://user-images.githubusercontent.com/6993072/156446114-107c43da-fe77-487b-92bb-828c8b0c0cf1.png)

**Comment by cmdrkotori** [comment]
Closing this because it was an upstream bug.
