### ISSUE TITLE
Save Window Layout

### ISSUE THREAD

**Issue by jojorne** [mpc-qt/mpc-qt#301]
I used to use MPC-HC with minimal layout.
Every time I open MPC-QT, it resets to normal layout.

**Comment by jojorne** [comment]
Just to make it clear, this is not "save geometry" as it save the position with the layout.

**Comment by tbertels** [comment]
It should save the layout.
It's saved in `/home/[user]/.config/mpc-qt/geometry_v2.json`

Here's an example when set to minimal:
`false` means it's hidden.
``` 
       "state": {
            "actionPlaySubtitlesEnabled": true,
            "actionPlayVolumeMute": false,
            "actionViewFullscreen": false,
            "actionViewHideCapture": false,
            "actionViewHideControls": false,
            "actionViewHideControlsInFullscreen": false,
            "actionViewHideInformation": false,
            "actionViewHideLibrary": false,
            "actionViewHideLog": false,
            "actionViewHideNavigation": false,
            "actionViewHidePlaylist": false,
            "actionViewHideSeekbar": false,
            "actionViewHideStatistics": false,
            "actionViewHideStatus": false,
            "actionViewHideSubresync": false,
            "actionViewOntopAlways": false,
            "actionViewOntopDefault": true,
            "actionViewOntopPlaying": false,
            "actionViewOntopVideo": false,
            "decorationState": 2,
            "shownStatsPage": 0
        }
```

**Comment by jojorne** [comment]
Yeah, it needs to separate the state from the geometry. The window frame is also not saved, but KDE can create window rules.

**Comment by tbertels** [comment]
Right now, the setting "Remember last window geometry" has to be enabled to restore the window layout.
If I understand it well, you'd want it to remember the window layout but not the geometry?

**Comment by jojorne** [comment]
> Right now, the setting "Remember last window geometry" has to be enabled to restore the window layout. If I understand it well, you'd want it to remember the window layout but not the geometry?

Yep! That include the Window Frame.

**Comment by tbertels** [comment]
That would also allow saving the window layout with Wayland, as we currently disable that setting when Wayland is used.
