### ISSUE TITLE
HDR Tone Mapping gets reset to 1.00 and labelled as "scale" on appimage boot but switching through drop-downs resets it to default

### ISSUE THREAD

**Issue by Sunspark-007** [mpc-qt/mpc-qt#310]
The default drop-down setting appears to be juncture 0.30 for Mobius.

Closing the app and re-opening it the value is displayed at 1.00 and labelled as "scale".

Switching through the drop-down items shows 0.30 and labelled as "juncture" instead of scale.

**Comment by tbertels** [comment]
Thanks for the report!
