### ISSUE TITLE
Framebuffer setting of 8 is bad

### ISSUE THREAD

**Issue by Sunspark-007** [mpc-qt/mpc-qt#311]
Used by the Plain and Low presets.. except it looks blocky like this:

![image](https://github.com/user-attachments/assets/0e02286c-4303-43a8-bf86-d966ef85bac1)

Higher settings look like this:

![image](https://github.com/user-attachments/assets/2f8134c8-c2e7-47a6-a9fe-e845933fd173)

The value displayed as "8" I think is actually a lower bit-depth..

Ok this is weird.. I tried playing some other vids and they seemed ok.. went back to this one and re-loaded the preset plain and applied it and it seems fine at 8.. 

So there is something.. but it didn't go back to how it was before with the lower bit depth.

**Comment by cmdrkotori** [comment]
I agree, 8 bits per color channel isn't ideal. However, the app starts out at settings that benefit lower powered devices. If your gpu is beefy enough there's no reason not to run it on the placebo preset all the time.

**Comment by Sunspark-007** [comment]
I wonder if the wording could be changed.. I was reading it wrong.. so 24 bit framebuffer is needed for RGB 0-255. Which means 32 float is the only option with alpha channel not needed since no releases contain that.

I wonder how 32 float works on a compositor that is set for 24 bit?

Curious that it didn't go back to the initial blocky appearance at 8.

**Comment by tbertels** [comment]
mpv's default framebuffer setting is `auto`: https://mpv.io/manual/stable/#:~:text=fbo-format=

> Default: auto, which first attempts to utilize 16bit float (rgba16f, rgba16hf), and falls back to rgba16 if those are not available. Finally, attempts to utilize rgb10_a2 or rgba8 if all of the previous formats are not available.

So we might want to rename the "Plain" preset to "Default" and add an "Auto" framebuffer entry at the top of the list.

**Comment by Sunspark-007** [comment]
Saw a note on a wiki that said "libplacebo requires the use of floating point buffers (to store unnormalized linear light data), and there is no quality gain from going above rgba16f". Probably applies to libmpv as well.
