### ISSUE TITLE
Seek bar should display a timestamp tooltip when moving the mouse over it

### ISSUE THREAD

**Issue by Sunspark-007** [mpc-qt/mpc-qt#315]
UI feature request.

Current behaviour in appimage 24.12 is that you must click on the square and drag it to see which timestamp position it is at, which forces it to play through the video as you drag it.

What is a better experience is to simply move the mouse over the bar without clicking and holding, and seeing a tooltip above it saying what mark it's at.. 1:00:04 or whatever. Every increment is already known since for static files the start and end is known.

**Comment by tbertels** [comment]
It's actually a Tweaks setting.
But I agree that it should probably be enabled by default. I think that's the case for mpc-hc.

**Comment by Sunspark-007** [comment]
So it is! Thanks! Yeah, for sure that should be enabled by default.
