### ISSUE TITLE
Add support of sreamlink just like GridPlayer and suggestions of alternatives to yt-dlp

### ISSUE THREAD

**Issue by trimechee** [mpc-qt/mpc-qt#319]
Hi, thanks's so much  for this great media player that i can use it in my windows 7 os 32 bits because generous Mr Adeii compile for me special last version of Mpc-QT for my wndows 7 os 32 bits ! : 

https://github.com/adeii/Qt6Win7/releases/download/Tests/mpc-qt-x86-24.12-Win7.7z

https://github.com/adeii/Qt6Win7/releases/tag/Tests

so yt-dlp can encounter bugs or problems for example youtube throttle yt-dlp, or get banned, so i think it's good to have an alternative like streamlink that can playback youtube videos, we hope please if possible add support for streamlink like this open-source media player GrdiPlayer did, because I and probably many others don't know how to use command lines of streamlink, choose video quality resolution..... thanks !

https://github.com/vzhd1701/gridplayer
https : //github.com/vzhd1701/gridplayer?tab=readme-ov-file#features

stream link stream-link
https://streamlink.github.io/
https://github.com/streamlink/streamlink

https://github.com/BellezaEmporium/query-streamlink
https://github.com/keystroke3/query-streamlink

GridPlayer has not been updated for over a year and we can't update it's internal yt-dlp, plus it is not compatible with my windows 7 os 32 bits, that's why i make this request !

if yt-dlp or streamlink are banned from github, I think it will be a good idea to add support for these engines similar to yt-dlp please to make this great media player even more exceptional and powerful ! :

https://github.com/iawia002/lux
https://github.com/soimort/you-get
https://github.com/LifeActor/ykdl

yt-dlp fork with in-between releases compatible with windows 7 os 32 bots, windows 8, vista.....
https://github.com/nicolaasjan/yt-dlp
--cookies-from-browser firefox
chrome --disable-features=LockProfileCookieDatabase --disable-features=NetworkServiceSandbox

ytdl-patched yt-dlp fork with some more features
https://github.com/ytdl-patched/ytdl-patched

https://github.com/pratikpatel8982/yt-dlp-mp4decrypt

https://github.com/un-def/dl-plus

**Comment by cmdrkotori** [comment]
This is the wrong place to make these suggestions.  Ask mpv devs to add these to libmpv.

**Comment by cmdrkotori** [comment]
No, mpc-qt only supports yt-dlp because mpv supports yt-dlp.  mpc-qt does not do much of anything special at all; mpv's networking code does all the heavy lifting.  If you want mpv based players to support other downloaders, file a bug report on mpv's bugtracker.
