### ISSUE TITLE
Wishlist: Transparent Seekbar and Volume slider background transparent

### ISSUE THREAD

**Issue by donga** [mpc-qt/mpc-qt#323]
This is my mpc-qt wishlist:
- Want the 'Seek bar' and 'Volume slider' has transparent background .

Here are the currents:
![Screenshot_20241221_102528-notransparent](https://github.com/user-attachments/assets/9a6ff040-4df6-4042-85a2-7b85f73e9374)
![Screenshot_20241221_102550-notransparent](https://github.com/user-attachments/assets/490b3f84-b012-4dcf-85c4-10b4df154e1d)

And the transparent i wish:
![Screenshot_20241221_102752](https://github.com/user-attachments/assets/2b5ae377-f2a6-44c3-b31c-90f435b349bf)
![Screenshot_20241221_102814](https://github.com/user-attachments/assets/f49f831e-a06a-4b05-9d12-6a6ac9f301c6)

Operating System: CachyOS Linux 
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.9.0
Qt Version: 6.8.1
Kernel Version: 6.12.6-2-cachyos (64-bit)
Graphics Platform: X11

Cheers,
Donga.

my mod:
```
--- mpc-qt-24.12/widgets/drawnslider.cpp	2024-12-07 17:52:20.000000000 +0700
+++ mpc-1t-24.12.mod/widgets/drawnslider.cpp	2024-12-21 09:43:29.586585891 +0700
@@ -344,8 +344,8 @@
     qreal pr = devicePixelRatioF();
     int pw = width() * pr;
     int ph = width() * pr;
-    backgroundPic = QImage(pw, ph, QImage::Format_RGB32);
-    backgroundPic.fill(bgColor);
+    backgroundPic = QImage(pw, ph, QImage::Format_RGBA8888);
+    backgroundPic.fill(Qt::transparent);
     QPainter p(&backgroundPic);
     p.scale(pr, pr);
 
@@ -470,8 +470,8 @@
     qreal pr = devicePixelRatioF();
     int pw = int(drawnArea.width() * pr);
     int ph = int(drawnArea.height() * pr);
-    backgroundPic = QImage(pw, ph, QImage::Format_RGB32);
-    backgroundPic.fill(bgColor);
+    backgroundPic = QImage(pw, ph, QImage::Format_RGBA8888);
+    backgroundPic.fill(Qt::transparent);
     QPainter p(&backgroundPic);
     p.scale(pr, pr);
```

**Comment by cmdrkotori** [comment]
Excellent idea!  What theme are using to test this with?

**Comment by donga** [comment]
> Excellent idea! What theme are you using to test this with?

i'm using kde 'lightly' (Bali10050 fork - now renamed to Darky) for application style,
'klassy' for window manager and last with 'GloriousDark_mod.colors' color-schemes.

my GloriousDark_mod.colors:
`[ColorEffects:Disabled]
Color=56,56,56
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=112,111,110
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=77,77,77
BackgroundNormal=101,101,101
DecorationFocus=49,91,239
DecorationHover=49,91,239
ForegroundActive=61,174,233
ForegroundInactive=189,195,199
ForegroundLink=41,128,185
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=222,222,222
ForegroundPositive=39,174,96
ForegroundVisited=127,140,141

[Colors:Complementary]
BackgroundAlternate=66,66,66
BackgroundNormal=51,51,51
DecorationFocus=49,91,239
DecorationHover=49,91,239
ForegroundActive=246,116,0
ForegroundInactive=136,136,136
ForegroundLink=49,91,239
ForegroundNegative=237,21,21
ForegroundNeutral=201,206,59
ForegroundNormal=222,222,222
ForegroundPositive=17,209,22
ForegroundVisited=49,91,239

[Colors:Selection]
BackgroundAlternate=79,127,239
BackgroundNormal=49,91,239
DecorationFocus=255,255,255
DecorationHover=255,255,255
ForegroundActive=252,252,252
ForegroundInactive=130,156,239
ForegroundLink=253,188,75
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=255,255,255
ForegroundPositive=39,174,96
ForegroundVisited=128,152,239

[Colors:Tooltip]
BackgroundAlternate=77,77,77
BackgroundNormal=51,51,51
DecorationFocus=49,91,239
DecorationHover=49,91,239
ForegroundActive=49,91,239
ForegroundInactive=189,195,199
ForegroundLink=49,91,239
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=222,222,222
ForegroundPositive=39,174,96
ForegroundVisited=127,140,141

[Colors:View]
BackgroundAlternate=48,48,48,240
BackgroundNormal=48,48,48,230
DecorationFocus=49,91,239
DecorationHover=49,91,239
ForegroundActive=49,91,239
ForegroundInactive=136,136,136
ForegroundLink=49,91,239
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=222,222,222
ForegroundPositive=39,174,96
ForegroundVisited=120,120,120

[Colors:Window]
BackgroundAlternate=66,66,66
BackgroundNormal=46,46,46,153
DecorationFocus=49,91,239
DecorationHover=49,91,239
ForegroundActive=49,91,239
ForegroundInactive=136,136,136
ForegroundLink=49,91,239
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=222,222,222
ForegroundPositive=39,174,96
ForegroundVisited=120,120,120

[General]
ColorScheme=GloriousDark_mod
Name=GloriousDark_mod
shadeSortColumn=true

[KDE]
contrast=4

[WM]
activeBackground=46,46,46,153
activeBlend=171,171,171
activeForeground=222,222,222
inactiveBackground=46,46,46,153
inactiveBlend=171,171,171
inactiveForeground=107,107,107
`

**Comment by tbertels** [comment]
@donga: Which font do you use? It looks pretty nice.

**Comment by donga** [comment]
> @donga: Which font do you use? It looks pretty nice.

I'm using font named: **Merriweather Sans** =>  [(https://fonts.google.com/specimen/Merriweather+Sans)]
With AntiAlias=true, Hinting=true, hintstyle=HintSlight, subpixel=rgb and LCD filter=lcddefault
:-)

**Comment by tbertels** [comment]
Thanks!
