### ISSUE TITLE
feat: Could a feature be added to automatically add all videos in the current playing file's folder to the playlist？

### ISSUE THREAD

**Issue by 876818701** [mpc-qt/mpc-qt#325]
Could a feature be added to automatically add all videos in the current playing file's folder to the playlist, just like the native MPV player does?

**Comment by cmdrkotori** [comment]
This already exists, although it isn't automatic.  Use `File->Open Directory` and it will add the contents of a directory to the open playlist.  Also, from dolphin/explorer, if you right-click a folder and open it with mpc-qt, the entire folder will be in the playlist.

**Comment by tbertels** [comment]
This is something I've thought about (Haruna does this).
It would make it easier to know which file will play next with the "play next file in folder" feature.
Though it would require to not play automatically (by default) the next file in playlist when the playlist was created this way.
It would probably also require a way to show in the playlist whether the next item in it will play automatically (if multiple files have been added manually or an option is enabled) or not.
