### ISSUE TITLE
Qt6?

### ISSUE THREAD

**Issue by ahjolinna** [mpc-qt/mpc-qt#37]
Now with [Qt6.3 released](https://www.qt.io/blog/qt-6.3-released) I was wondering is there any plans for Qt6 port?

(also Qt has now moved from qmake to cmake)

**Comment by cmdrkotori** [comment]
I think we'll be staying on Qt 5 for a bit because some distros aren't shipping Qt6 yet.

**Comment by ahjolinna** [comment]
true, there is no real hurry as Qt 5.15.x (LTS) just got its support extended by an additional two more years...and I'm not sure if all Qt modules have been ported yet to Qt6, maybe with v6.4 which should be the next LTS release

**Comment by cmdrkotori** [comment]
Some apps I use (such as focuswriter) have ported themselves Qt6, but they lack kde's thumbnail file-picker. As soon as KDE ports the filepicker to Qt6, I might make a switch.
