### ISSUE TITLE
[Request] Support for dragging & dropping subtitle files

### ISSUE THREAD

**Issue by r2rX** [mpc-qt/mpc-qt#38]
Greetings,

Cheers for this great program. Users accustomed to/coming from Windows, that use MPC-HC, will feel right at home with this.

Speaking of which, there is a feature of MPC-HC that allows a user to drag & drop any subtitle file into the player and have it loaded immediately. At the moment, mpc-qt (at least from my experience) can only load subtitle files that are in the same folder as the video playing and requires the subtitle file name to match the video name.

If it were possible to add support for drag & dropping a subtitle file, irrespective of its file name, that would be fantastic!

Cheers!

**Comment by r2rX** [comment]
Hey @cmdrkotori . Just wanted to give some feedback. I compiled & installed the latest git (22.02-27-g9232807) and tested dragging & dropping a subtitle file. The moment the subtitle is dropped into mpc-qt, the video running seems to pause/halt for a few seconds and then it plays quickly to recover to the time stamp the delay caused....and no subtitles are displayed (renaming the subtitle file to the video's filename doesn't make a difference). However, mpc-qt now automatically loads subtitles, that are not named the same as the video, as long as the subtitle file is placed in the same folder as the video. Lastly, I tried dragging & dropping the subtitle file while in the same folder as the video....the same pause/halt occurs but as it already loaded the subtitle the moment the video opened, I don't know whether it would have worked or not.

 Testing was done on Fedora 35 KDE running Wayland.

**Comment by cmdrkotori** [comment]
Is the subtitle added to the subtitles submenu?
Do you have a torrent/dl with subtitle files in it so I can test?

**Comment by r2rX** [comment]
> Is the subtitle added to the subtitles submenu? Do you have a torrent/dl with subtitle files in it so I can test?

After dragging & dropping the subtitle file, it is not added to the subtitles menu. If you want to test, download any .mp4 video, for example, and download any random subtitle (.srt) just for the sake of testing.

**Comment by r2rX** [comment]
Hi @cmdrkotori , this didn't occur to me at the time when I submitted this request but my system is running on Wayland by default (and not X11). Does this fix apply to X11 only?

**Comment by r2rX** [comment]
Not sure what changed on my system exactly, whether it's a Qt update or another related library but dragging and dropping subtitle files seems to be working fine now. :+1: Cheers @cmdrkotori !

**Comment by cmdrkotori** [comment]
np
