### ISSUE TITLE
can't play Sony atrac9 (.at9) files in mpc-qt (mpv plays them fine)

### ISSUE THREAD

**Issue by poudink** [mpc-qt/mpc-qt#41]
Title says it all. Selecting an at9 file just doesn't do anything in mpc-qt. mpv plays them no problem. Since mpc-qt is supposed to be using mpv, that's pretty weird. I also noticed the same thing with MIDI files, but mpv's MIDI support is so bad it doesn't really matter.

**Comment by cmdrkotori** [comment]
Please provide an at9 file for me to test.

**Comment by cmdrkotori** [comment]
Lacking any test file, this should be fixed in git master.

**Comment by poudink** [comment]
[bgm_login.at9.zip](https://github.com/mpc-qt/mpc-qt/files/8744871/bgm_login.at9.zip)
I can't test the new version yet, so here's a test file just in case. Sorry for not providing earlier.

**Comment by cmdrkotori** [comment]
It seems that file has invalid pts (the displayed time is incrementing much faster than real time), so something is wrong with the file. Audio plays fine despite that. I would check that the application is not muted though.
