### ISSUE TITLE
Change fullscreen mode to borderless windowed

### ISSUE THREAD

**Issue by megapro17** [mpc-qt/mpc-qt#42]
I tried searching it in settings, but fullscreen options are greyed out

**Comment by cmdrkotori** [comment]
I'm not aware that qt lets us easily do that. Labelling as an enhancement anyway because perhaps one day I'll write enough code for a work-around.

**Comment by cmdrkotori** [comment]
According to a recent test, it seems that the Qt6 edition on Windows 11 uses borderless windowed mode. Closing for now.
