### ISSUE TITLE
Remembering video position?

### ISSUE THREAD

**Issue by gaspardleon** [mpc-qt/mpc-qt#44]
Remembering the where you were upto last time you played the file?

I don't know if this is already a feature and I'm just dumb...

But it would be nice to be able to auto-start playback at the last played position in the file... if possible.

Love the program so far, seems like it will be a nice replacement for mpc-hc for me!

**Comment by gaspardleon** [comment]
Not to be a pest, but also how to go next file in folder... I tried to assign a key to it but it didn't have an effect... in mpc-hc you just click skip forward and it jumps to the next file

**Comment by cmdrkotori** [comment]
Tagging this as a feature request for now.

Regarding your second question, you need to tell mpc-qt to change the way it handles single-entry playlists.
![Screenshot_20220822_120359](https://user-images.githubusercontent.com/65291121/185824812-9ce95632-6f03-4201-941f-9f13aa2605d0.png)

**Comment by gaspardleon** [comment]
Thank you for your swift response!

**Comment by githottub** [comment]
I see this issue is still in open status. So, does that mean, for example, if I'm watching a long video with MPC-QT and want to stop and watch the remainder another time, it won't remember the position where it stopped? Every other player I know of has had this ability for many years. If MPC-QT still doesn't, add another vote for it as a feature request. I think it is an important basic feature to have. Thanks for your consideration and continued improvement of this software.

**Comment by cmdrkotori** [comment]
You can use the favorites feature to remember a particular position in a video. This works right now, even when an item is removed from the playlist.

As for this feature request, remembering last played position of items in the playlist requires a few architectural changes.

**Comment by mnandzik** [comment]
I agree with githottub, this feature is mandatory for everyone and is the most important one just after the ability to play files. I'm very happy with this software as no one use multi playlists (as I know) on linux. (No potplayer on linux). I vote for this feature to be implemented as soon à possible.

**Comment by tbertels** [comment]
Note that the recent.json file already has a value for the last position of each file.
And if you set to something else than 0 (seconds), it opens the file at that position.

So the part that's missing is saving the position when the file is closed (including when the player itself is closed).
And an option to both both remember and reopen the last position when enabled.
