### ISSUE TITLE
Invisible Open subtitle window

### ISSUE THREAD

**Issue by mysuf** [mpc-qt/mpc-qt#45]
MPC-QT clone and build: 19 Jul 2022
Ubuntu 22.04.1
Radeon 5600XT (oibaf drivers)

I opened video file with MPC-QT, clicked Load Subtitles and I could see at bottom bar that there are 2 windows (player itself and Open subtitle), but Open subtitle window wasn't visible neither focusable. Closing the player at this moment by X icon didn't work however hitting CTRL+ALT+DEL(now you know where I came from) backdrop to switch user killed the process. 

The weird thing happened when I tried another approach to drag subtitles there by mouse. It worked and appended subtitles to subtitle list, but it didn't make them active - I had to switch it manually. However at this moment, clicking Load Subtitles showed Open subtitle window as expected. It looks like that default state of subtitles is somehow broken.

The bug is reproducible on my system (according to first text block) and it doesn't matter which video file I open.

Otherwise really cool player! Far above VLC. Package deployment for major distros would be really appreciated (if it wouldn't cause noticable perf regression ofc).

P.S. Just found out that when player is stucked with that subtitle window hidden, when I open another video file which change source of the player, Open subtitle window magically appears on top, but it doesn't respond to clicks and moment later popup says that mpc-qt doesn't respond and if I want to force quit. Mouse drag approach doesn't cause this dead lock.

**Comment by cmdrkotori** [comment]
>Closing the player at this moment by X icon didn't work however hitting CTRL+ALT+DEL(now you know where I came from) backdrop to switch user killed the process.

This is likely because the load subtitle window is a modal window. This means it grabs application focus. The way out of this situation is to the close the modal window. It's what happens on Windows when the file selection dialogs are used. No way around it.

Other applications can behave the same way too. Google says the following:

>A modal (also called a modal window or lightbox) is a web page element that displays in front of and deactivates all other page content. To return to the main content, the user must engage with the modal by completing an action or by closing it.

Next time this happens, close the sub window and all will return to normal.

**Comment by cmdrkotori** [comment]
>Otherwise really cool player! Far above VLC.

Thanks for the kind words!

>Package deployment for major distros would be really appreciated (if it wouldn't cause noticable perf regression ofc).

This won't happen by my hand. I'm not a package maintainer and try my hardest not to be one: I'm a developer not a package maintainer. The most I'll ever do I think is a windows release on the releases page and perhaps a flatpak. Hope that clears things up.

There's a package on the AUR and in bsd ports. If you're running a debian based distro follow the compile+install instructions and you'll get a binary under /usr/local/bin. I have no experience with other distros, sorry.

**Comment by mysuf** [comment]
I knew that CTRL+ALT+DEL will draw attention. It was just a side effect I described when trying to close the app.

Tell me how to close sub window (or modal) that is invisible and not focusable. :) It's UI dead lock. I can capture a video, but believe me, this is not how other applications behave. It's clearly a bug.
