### ISSUE TITLE
Can't seem to enable a few options

### ISSUE THREAD

**Issue by dummifiedme** [mpc-qt/mpc-qt#47]
I was looking around in the settings, and I noticed, many of the settings are greyed out for me. I especially needed the subtitle downloader, but it seems to be greyed out as well. Is it intentional?

I am on an Arch-based Manjaro Linux with KDE and I built it from source via AUR.

![image](https://user-images.githubusercontent.com/68785729/187060209-23141068-a2d0-4509-ad4f-6f4cc4102b60.png)
![image](https://user-images.githubusercontent.com/68785729/187060220-457811b1-4623-4bd5-b989-63b1ba6aab5d.png)

**Comment by cmdrkotori** [comment]
Those settings are grayed out because the code for them isn't written.
