### ISSUE TITLE
Error compiling on Fedora; qtx11extras missing but is installed

### ISSUE THREAD

**Issue by r2rX** [mpc-qt/mpc-qt#48]
Hello there,

I was trying to compile the latest snapshot of mpc-qt on Fedora 36 KDE of which I encountered an error in the qmake process: _Project ERROR: Unknown module(s) in QT: x11extras_. The package name, in the Fedora repo, is _qt5-qtx11extras-devel_ (v5.15.5) which is installed and accounted for. Could the error be that the compile process is looking for a specific name for x11extras that Fedora isn't naming in the same way?

**Comment by cmdrkotori** [comment]
x11extras is the correct name of the qt module. Fedora must have a broken package. I would suggest you install any other distro which doesn't have that problem.

**Comment by r2rX** [comment]
Hey @cmdrkotori . That's interesting as I had compiled build g9232807 not too long ago with no problem. When checking the file names for the x11extras-devel package, it lists as follows:

```
/usr/include/qt5/QtX11Extras
/usr/include/qt5/QtX11Extras/QX11Info
/usr/include/qt5/QtX11Extras/QtX11Extras
/usr/include/qt5/QtX11Extras/QtX11ExtrasDepends
/usr/include/qt5/QtX11Extras/QtX11ExtrasVersion
/usr/include/qt5/QtX11Extras/qtx11extrasglobal.h
/usr/include/qt5/QtX11Extras/qtx11extrasversion.h
/usr/include/qt5/QtX11Extras/qx11info_x11.h
/usr/lib64/cmake/Qt5X11Extras
/usr/lib64/cmake/Qt5X11Extras/Qt5X11ExtrasConfig.cmake
/usr/lib64/cmake/Qt5X11Extras/Qt5X11ExtrasConfigVersion.cmake
/usr/lib64/libQt5X11Extras.prl
/usr/lib64/libQt5X11Extras.so
/usr/lib64/pkgconfig/Qt5X11Extras.pc
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri
```

I don't think Fedora changed the file names of the package over the last few months. If it is indeed a name mismatch (or perhaps a case-sensitivity error), which file from the source can I check to confirm this?

**Comment by r2rX** [comment]
Hi @cmdrkotori . I recalled how to compile it on Fedora. The compiling instructions provided on the main page apply except after cloning the git, run _**qmake-qt5**_ rather than _qmake_. Hope this will help other Fedora users who get stuck at this point.
