### ISSUE TITLE
Copy the displayed subtitle to the clipboard

### ISSUE THREAD

**Issue by Letor123** [mpc-qt/mpc-qt#5]
I am using the player for learning another language. It is necessary for me to copy the displayed subtitle on the screen and past it to my text editor. This is because the displayed subtitle introduces a new word which needs to be taken care of regarding my vocabulary. So, it would be a great help if you can add the feature to the player. It also helps if user can assign a shortcut key to this feature in the Option menu.

Thanks a lot,
OL

**Comment by cmdrkotori** [comment]
I don't think libmpv has this feature, sorry.

**Comment by cmdrkotori** [comment]
Turns out we can monitor the `sub-text` property and copy that to clipboard. Expect a patch on git head soonish.

**Comment by cmdrkotori** [comment]
The shortcut for this new feature is Ctrl+S.
