### ISSUE TITLE
No loop function?

### ISSUE THREAD

**Issue by Impeta** [mpc-qt/mpc-qt#50]
I don't think I can find anywhere the option to simply keep a video on loop forever. Is there one? I tried After Playback > checking Repeat within section Every Time, though it won't save the option after the player loops the video.

**Comment by BillFleming** [comment]
In the Playback->Playlist menu the "Repeat forever" option works on both audio and videos just fine (also repeats same video in playlist), but you have to go into this menu to turn it on or off it seems. Believe that MPC-HC just had a toggle switch in the control bar.

**Comment by cmdrkotori** [comment]
In mpc-hc there's a setting in the menu.  The problem is repeat file and repeat Playlist are missing from mpc-qt.

![Screenshot_20240424_161301](https://github.com/mpc-qt/mpc-qt/assets/65291121/086fb9e2-03ee-42bb-8452-8dfa9f0a4ab4)

**Comment by tbertels** [comment]
Here's the After Playback menu in mpc-qt:

![Copie d'écran_20240823_131649](https://github.com/user-attachments/assets/4cfa77fe-e30c-4984-b8dc-d19a20e02935)

And in mpc-hc for comparison:

![Clipboard 2](https://github.com/user-attachments/assets/aabf382a-9055-4c9e-ace5-5f67b9e205e3)

So maybe the Repeat commands should be moved to a new Repeat submenu with a new Playlist entry and a "Forever" toggle.

By the way, the "Forever" commands don't make much sense right now as they don't get saved across launches.
