### ISSUE TITLE
[Feature Request] Enable option to select hardware output API & Wayland DMABUF

### ISSUE THREAD

**Issue by r2rX** [mpc-qt/mpc-qt#54]
Hello there,

[MPV 0.35](https://github.com/mpv-player/mpv/releases/tag/v0.35.0) was released quite recently and exposes a few nice options (i.e direct pipewire support, which current mpc-qt picks up) as well as Vulkan support. There's also the vo_dmabuf_wayland back-end that allows for Wayland video output displaying using DMA-BUF buffers for efficient displaying when using the VA-API or DRM hardware decoding support.

So is it possible to add an option to choose between OpenGL and Vulkan, as well as an option to toggle on/off vo_dmabuf_wayland?

Thanks!

**Comment by cmdrkotori** [comment]
As far as I know, we're stuck with using an opengl renderer. libmpv lacks a way of us providing it a client-side vulkan context.

Technically we can embed a player window and get access to other renderers, (such as vo_dmabuf_wayland et al,) however drawing a logo in the player area during idle becomes a kludgy hack (layered sub-windows with changing z-order) compared to the elegance of an opengl context we can draw our own content on. So I'd rather not go back to that method if I can help it.

Thanks for asking.

**Comment by r2rX** [comment]
> As far as I know, we're stuck with using an opengl renderer. libmpv lacks a way of us providing it a client-side vulkan context.
> 
> Technically we can embed a player window and get access to other renderers, (such as vo_dmabuf_wayland et al,) however drawing a logo in the player area during idle becomes a kludgy hack (layered sub-windows with changing z-order) compared to the elegance of an opengl context we can draw our own content on. So I'd rather not go back to that method if I can help it.
> 
> Thanks for asking.

Ah. So assuming selection for Vulkan client-side context and vo_dmabuf_wayland were exposed options in libmpv, then it would be possible? If that's the case, perhaps I could open a thread on the mpv thread requesting it.

**Comment by r2rX** [comment]
Hey @cmdrkotori . Despite the delay, I made a [post](https://github.com/mpv-player/mpv/issues/11031) on mpv's git page. Just referencing it here in case you're interested and/or your direct feedback would be helpful in the discussion.

**Comment by ahjolinna** [comment]
I was wondering was this ever implemented? as the HDR protocol for Wayland is about to be merged  https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/14#note_2777587

and for mpv you need "-vo=dmabuf-wayland" for it to work

**Comment by tbertels** [comment]
Does `mpv --vo=dmabuf-wayland [file]` actually works on your system?
It requires Wayland obviously but also compatible GPU, drivers and compositor and [it's experimental](https://mpv.io/manual/master/#video-output-drivers-dmabuf-wayland).

**Comment by tbertels** [comment]
Reopening to make it clear that this isn't yet supported.
