### ISSUE TITLE
The video frame is not centered, it is in the lower left corner

### ISSUE THREAD

**Issue by Luyiay** [mpc-qt/mpc-qt#59]
The video is displayed in the lower left corner and the logo at startup is displayed in the lower right corner.How can I correct it

**Comment by Luyiay** [comment]
My English is not good,I can only roughly understand the options in the settings, and trying to change a few options but doesn't work

**Comment by Luyiay** [comment]
I found that it was back to normal after setting kde's global scaling to 100%, but this scaling rate was too small for me

**Comment by cmdrkotori** [comment]
HiDpi bug. IIRC Qt5 only has integer scaling (100%,200%,300%,etc). This might be fixed should we update to Qt6, though I haven't looked at that seriously at the moment.

**Comment by cmdrkotori** [comment]
Logo placement is fixed in master.
