### ISSUE TITLE
Subtitle feature misisng

### ISSUE THREAD

**Issue by elliotphoenixpry** [mpc-qt/mpc-qt#6]
Both **mpv** and **mpc** have subtitle back color
https://mpv.io/manual/stable/#options-sub-back-color
It's nice to **mpc-qt** add this feature

Also adding alpha to subtitle color selectors will be very good

Very good project, Thank you

**Comment by cmdrkotori** [comment]
Fixed in cbb5bb423249657dd35bcb69835c25d6e705a6ce.
