### ISSUE TITLE
Stretch video to full screen.

### ISSUE THREAD

**Issue by kennyrose666** [mpc-qt/mpc-qt#62]
There is no way to stretch 21:9 video to full screen in 16:9 format

**Comment by cmdrkotori** [comment]
Is this stretched disregarding aspect ratio, or stretched with sides chopped off?

**Comment by kennyrose666** [comment]
I'm sorry, I didn't really understand your question. Here's the thing, I'm downloading a widescreen movie from a torrent, and I have black bars (aka letterbox) on top and bottom of the screen when viewing, I would like to stretch the movie vertically so that it occupies the entire screen area, but I didn't find such an opportunity
