### ISSUE TITLE
Playlist for iptv

### ISSUE THREAD

**Issue by trimechee** [mpc-qt/mpc-qt#63]
Hello, thank you so much for this wonderful amazing media player !

Please i have request : it will be great to have playlist manager and we can bookmark tv channels easily and rearrange them in a great interface comparable to iptv players, thank you very much! I tried vlc player but I can't save my favorite tv channels, I tried several media player friends none of them offers a clear playlist comparable to iptv players! many iptv players are not updated or are not open source, it is very difficult to find reliable ones and that's why I would just like to use a media player to play my iptv, thank you so much !

**Comment by cmdrkotori** [comment]
iptv has worked in mpv and by extension mpc-qt for years. You can open a network stream with `File->Open Network Stream`. However this functionality at present **replaces** the _quick playlist_ with a single-item playlist, even when another playlist is selected. The expected behavior would be to manipulate whatever playlist is selected and add it like a regular item.

I'll see if the network stream command can be fixed to be more playlist friendly.

In the meantime if you're using KDE and the latest release, you can use `File->Quick Add To Playlist` and paste the url in the quick open dialog's name field. This adds it as a regular item to the active playlist as you would expect.

**Comment by trimechee** [comment]
Great marvellous fantastic ! Thank you very much for yout precious help ! 🥇 💯 

I use windows 10 and i will try in sha Allah ! 

Please i have other suggestion : 
We konow there is the famous yt-dlp, thay's great and my suggestion is in order to play videos from even more and more streaming web sites and possibly avoid future eventual yt-dlp bugs or banishment or censorship agianst yt-dlp ... my suggestion is to add support for these awesome downloader engines if it is technically possible, thank you very much !

https://github.com/selsta/hlsdl

https://github.com/nilaoda/N_m3u8DL-CLI

https://github.com/nilaoda/N_m3u8DL-RE

https://github.com/soimort/you-get

https://github.com/iawia002/lux

https://github.com/nilaoda/BBDown

https://github.com/Momo707577045/m3u8-downloader/blob/master/README-EN.md
https://github.com/Momo707577045/media-source-extract

https://github.com/acolwell/mse-tools

https://github.com/globocom/m3u8

https://github.com/dodying/UserJs/tree/master/novel/novelDownloader

https://github.com/hoothin/UserScripts

https://github.com/Momo707577045/m3u8-downloader/blob/master/README-EN.md

https://github.com/acolwell/mse-tools

https://github.com/kanishka-linux/hlspy

**Comment by cmdrkotori** [comment]
You'll have to ask the @yt-dlp devs (or @mpv-player devs) if they will support what those downloader tools do. We're simply a front-end to libmpv.

**Comment by trimechee** [comment]
Yes ! but i think  projects like "you-get" and "lux" are independent competing indie projects rivaling yt-dlp project, does Mpc-qt compatible with yt-dlp?

**Comment by cmdrkotori** [comment]
As far as I know, libmpv (the library we use to play video) only supports yt-dlp.

**Comment by trimechee** [comment]
Awesome ! yt-dlp is already very stable and good, thank you :)

**Comment by trimechee** [comment]
It id not possible to integrate natively streamlink program in Mpc-qt like Gridplayer please ?

Girdplayer has integrated this software streamlink :
https://github.com/vzhd1701/gridplayer#features 
https://github.com/streamlink/streamlink

**Comment by cmdrkotori** [comment]
>It id not possible to integrate natively streamlink program in Mpc-qt like Gridplayer please ?

That has to be done on the backend, in libmpv, the right place for it. Hacking streamlink support into mpc-qt is unwanted complexity for me that would merely serve to duplicate whatever code inevitably ends up in libmpv. Ergo, it would be a waste of my time.

**Comment by trimechee** [comment]
I understand, there s no problem :)  anyway i finally figured out how to use streamlink because i couldn't and now i learned how to use streamlink even if its not as easy as 3DYD Youtube Source....
