### ISSUE TITLE
Trim invalid characters and length for screenshot filenames on Windows

### ISSUE THREAD

**Issue by mfsoup** [mpc-qt/mpc-qt#65]
Any stream containing invalid characters (such as ? on Youtube urls) cause auto screenshots on Windows to not work, with the only option being to change the file name manually in save image. Long m3u8 urls can also cause screenshots to not save because of the filename being too long.

**Comment by cmdrkotori** [comment]
Do you have a sample of a really long m3u8 that I can use to debug this?

**Comment by cmdrkotori** [comment]
Should be fixed in master, although I don't have a file long enough to properly test this. If it is still giving you a hassle after the next release, give me a ping here.

**Comment by cmdrkotori** [comment]
You could also try https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/, which should fix this problem in more places, should those apps be smart enough to support it.
