### ISSUE TITLE
mpc-qt 23.02 not launching / segfaulting on windows

### ISSUE THREAD

**Issue by goyalyashpal** [mpc-qt/mpc-qt#66]
When launching mpc-qt on windows 10 20H2 by double clicking from explorers, it doesn't launch. I tried launching via shell, it showed segmentation fault.

version used is: [mpc-qt-win-x64-2302.zip]

[mpc-qt-win-x64-2302.zip]: https://github.com/mpc-qt/mpc-qt/releases/download/v23.02/mpc-qt-win-x64-2302.zip

**Comment by cmdrkotori** [comment]
Works on my machine.

![image](https://user-images.githubusercontent.com/65291121/227474967-c8d16874-e67d-4dd4-8122-d2b9dcdbf7fe.png)

I have Windows 10 22H2.

**Comment by goyalyashpal** [comment]
so, what can i do? 🤔

**Comment by cmdrkotori** [comment]
>so, how to troubleshoot then?

1. Use git master.
2. Follow the installation instructions in the Windows section of the README.
3. Run a debug build from qtcreator and screenshot the backtrace.
