### ISSUE TITLE
rewind when playing audio file

### ISSUE THREAD

**Issue by iswritergeek** [mpc-qt/mpc-qt#73]
at the moment there's no ability to rewind an audio file when playing it through mpc-qt, and attempting to fast-forward can yield...interesting results.

in mpv, there's the ability to "step back/forward" through a file by 5-10 seconds by using the scrollwheel. i use it *a lot* when I'm transcribing files.
it would be nice if there was an option to toggle between using the scrollwheel for either volume control or for stepping through the file, especially when it's an audio file.

**Comment by cmdrkotori** [comment]
Go to the keys page in the options dialog and set wheel up and wheel down to seek forwards / seek backwards.
![Screenshot_20230606_194722](https://github.com/mpc-qt/mpc-qt/assets/65291121/ce81da8b-ad00-4af8-9f45-fa3ddc290d3f)
1. Select desired item in mouse column, three buttons will appear over the item
2. Press B button, select Wheel
3. Press ^v button, select Up/Down
4. Press Apply when done

Note there is a difference between "Mouse Window" and "Mouse Fullscr", one is active for windowed mode, the other is for fullscreen.
