### ISSUE TITLE
Cannot play next/previous in folder, stops playback instead (windows)

### ISSUE THREAD

**Issue by leonardo-squeef** [mpc-qt/mpc-qt#74]
In MPC-HC, the default behavior of the "previous" and "next" keybinds (defaults pg up and pg down respectively) is to play the next or previous file in the same folder. In mpc-qt, it stops playback entirely. I'm only able to reproduce MPC-HC's default behavior when I open a directory instead of a single file. Same thing occurs when using the skip buttons on the menu bar. Is this intended behavior?

**Comment by cmdrkotori** [comment]
Turn this option on.
![Screenshot_20230620_160526](https://github.com/mpc-qt/mpc-qt/assets/65291121/2c058a02-5928-40a0-915c-f4dfa59d9b23)
