### ISSUE TITLE
Windows Settings Location Not Portable

### ISSUE THREAD

**Issue by githottub** [mpc-qt/mpc-qt#75]
Since this is distributed for Windows as portable (i.e. not installed) is there a way to store the settings files in the same folder as MPC-QT rather than it creating a folder in C:\Users\ ... \AppData\Roaming

This would provide the benefit of it being truly portable and it could, for example, be stored on a thumb drive and used on other PCs. If there is currently no method to achieve this, please consider it a feature request. Thank you for your continued improvement of this software.

**Comment by cmdrkotori** [comment]
Fixed in 6676af8aa505160d9e2447c376a9f6803c5d27e3

Create portable.txt (any size) in the executable's folder.
