### ISSUE TITLE
ui is illegible/theme not applying properly

### ISSUE THREAD

**Issue by ezvision** [mpc-qt/mpc-qt#76]
For some reason the player appears like this for me. I've tried messing around with some of the display settings/colors but can't figure out why it's like this.
![Screenshot from 2023-07-02 00-16-16](https://github.com/mpc-qt/mpc-qt/assets/31146313/faa6330b-a7f8-4332-95d7-f5ac3e9877f6)

I'm on linux, fedora 38.

**Comment by ezvision** [comment]
I'm on linux, fedora 38.

**Comment by cmdrkotori** [comment]
It appears that qt's svg plugin is not installed. If it's from the latest release, it's qt5-qtsvg. If its' git master, it's qt6-qtsvg.

**Comment by ezvision** [comment]
Installing qt5-qtsvg fixed it, thanks!
