### ISSUE TITLE
Support of hlsdl 

### ISSUE THREAD

**Issue by trimechee** [mpc-qt/mpc-qt#79]
Hello, it will be great to add support of hlsdl beacause hlsdl solves some bugs in ffmpeg according to some users... it will be great to add support for this software, thank you very much !

https://github.com/selsta/hlsdl

".HLSDL appears working much better than ffmpeg in these cases.
Hlsdl is public and the source code available.
The stream plays almost immediately and is stable. No errors or buffering.
Using ffmpeg for the download step gives a very long intial delay and is not very stable.
so I assume that the new crypto+hls RAI flows are badly handled by ffmpeg based players now.....

the video is choppy and unable to buffer enough for a fluid vision. Parole has no problem.

FFmpeg is not good for HLS streams, but I watched a lot of various HLS streams without any problems. The main problem is that FFmpeg downloads all streams (many video sizes at once), so you can watch only HLS stream with single video size"

**Comment by cmdrkotori** [comment]
Out of scope for us. Make this feature request upstream to mpv.

**Comment by trimechee** [comment]
Very interesting, I understand :) and Mpc-qt is already complete and awesome, thank you 👍

**Comment by trimechee** [comment]
Hello @cmdrkotori , is it possible to add support of streamlink for live streams please ? Gridplayer has succeded to add streamlink to vlc player..... 


 



https://streamlink.github.io/thirdparty.html


https://github.com/back-to/liveproxy



https://github.com/back-to/generic

**Comment by cmdrkotori** [comment]
That's out of scope for this project. You'll have more success bugging mpv about it.

**Comment by trimechee** [comment]
We undestand , thank you :) i use GridPlayer but GirdPayer doesn't have yet auto updater for streamlink and i wish to use the last version of streamlink that's why i make this request for Mpc-qt.....bit yt-dlp is powerful and sufficient, thank you :)
