### ISSUE TITLE
Add new updated MPC-HC and MPC-BE

### ISSUE THREAD

**Issue by trimechee** [mpc-qt/mpc-qt#80]
Hello, in description of our beloved Mpc-qt, it is said  : 

"Media Player Classic Home Cinema is considered by many to be the quintessential media player for the Windows desktop. Media Player Classic Qute Theater (mpc-qt) aims to reproduce most of the interface and functionality of mpc-hc"

The sad news is that MPC-HC is not under development since 2017 :(

but the good news there is a new version of mpc-hc that it is actively updated and enhanced by Mr clsid2 

https://github.com/clsid2/mpc-hc

and there is anoher frequently updated media player that is based on mpc-hc, i mean MPC-BE made by Mr Aleksoid1978 and friends :  

https://github.com/Aleksoid1978/MPC-BE
 

It will be great if our beloved MPC-QT will be based on these frequently updated players ! Thank you so much :)

**Comment by cmdrkotori** [comment]
We already try to do this. The ui we follow is mostly mpc-hc (classic and updated), a bit of mpc-be, a bit of vlc, a bit of clementine.

**Comment by trimechee** [comment]
That's sensational wonderful ! Thank you so much :) 💯 🥇
