### ISSUE TITLE
Add left mouse button click option to play/pause the video

### ISSUE THREAD

**Issue by trimechee** [mpc-qt/mpc-qt#82]
Hello, for a more comfortable and faster playback, we will be so grateful if mpc-qt adds this option : left mouse button click allows to play / pause the video, thank you so much !

**Comment by cmdrkotori** [comment]
Already implemented

**Comment by trimechee** [comment]
Great ! 🥇  I said that because when I open a local file or a streaming video, I playback the video then I quit the video by closing the media player then I open it again, and when I want to resume playing the video and I click with the left mouse button, nothing happens that's why I asked for this option, and therefore you have to go to the bar at the bottom to be able to play the latest video mias unfortunately our beloved mpc-qt doesn't remember playback position and playback starts from the beginning of the video, it will be great to add an option "remember playback position of last played file" while allowing left mouse button instant replay of the last video played, thank you very much !
