### ISSUE TITLE
libmujs.dll missing on latest Windows action artifact

### ISSUE THREAD

**Issue by mfsoup** [mpc-qt/mpc-qt#91]
https://github.com/mpc-qt/mpc-qt/actions/runs/5973052757

This artifact doesn't launch because libmujs.dll is missing. Downloading it manually from MSYS2 packages fixes the issue.

![mujs](https://github.com/mpc-qt/mpc-qt/assets/38110452/39a3c3c1-5431-41f3-9366-47099c3e4ec1)

**Comment by cmdrkotori** [comment]
Fixed in 4b73ee71b22d08cbf19a07e26b4b0dc69108893e.
