### ISSUE TITLE
"Prefer external subs" prevents me from changing the subtitle track

### ISSUE THREAD

**Issue by Yasand123** [mpc-qt/mpc-qt#93]
When the setting `Prefer external subtitles over embedded subtitles` is checked, changing the subtitle track does nothing, it locks it to the external subtitle. Unchecking the setting allows me to pick another subtitle from the subtitles list (or by hitting S on the keyboard).

To me this setting shouldn't lock the ability to change the subtitle track, this feels like an unintended behavior. It should only load external subs by default.

**Comment by cmdrkotori** [comment]
Fixed in e79e785a9d85678332b3b225c31bcddbe337e4fd.
