### ISSUE TITLE
Can't play videos from my.mail.ru/video  

### ISSUE THREAD

**Issue by trimechee** [mpc-qt/mpc-qt#96]
Hello,  yt-dlp  support downloading videos from https://my.mail.ru/video  but Mpc-Qt can't play video from this  famous important  streaming website, we hope there will be fix soon please, thank you so much  :)

https://my.mail.ru/v/sienduk/video/35/707.html

I specify that I encountered this bug with several other media players that use yt-dlp....

My favorite streaming site posts its videos on this email site. ru and mail media player. ru is one of the few to offer ideal 360p quality when our connection is weak and this helps avoid lag, freezes, jerks.... that's why I talked about this bug because it's a mportant site and the streaming videos are not deleted....and we are no longer obliged to use a heavy web browser to watch the streaming videos since the media players can do it, hence my request....

Thank you !

**Comment by cmdrkotori** [comment]
Works on my machine.

Use File -> Open Network Stream -> paste the url in the box

**Comment by trimechee** [comment]
Interesting and very important information , thank you @cmdrkotori   :) Is there a log option in our beloved Mpc-qt to copy and paste the error logs I encounter and post them here please?.....all players that i tried fails, only qmplay2 succeded ti fix this bug after i talk to the developer who was able to fix this bug....

**Comment by cmdrkotori** [comment]
To view the logs use view->log

If you're on Windows it's possible that you might have an ancient version of yt-dlp in your executable folder.

**Comment by trimechee** [comment]
Thank you for your help :) @cmdrkotori

**Comment by trimechee** [comment]
@cmdrkotori Ohh yeahh ! i can play video from mail . ru wih the new awesome version of Mpc-Qt !! Thak you so much ! 🥇 

our hope now is  intgrating the wonderful Uosc to choose stream quality , it will be great to make Mpc-qt even more easy and simple to use for beginners and crowds to add this program natively and it will allow beginners to choose easily the desired streaming video quality, thank you very much!

Feature-rich minimalist proximity-based UI for MPV player:

https://github.com/tomasklaen/uosc

https://github.com/natural-harmonia-gropius/mpv-config

https://github.com/christoph-heinrich/mpv-quality-menu
